/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: libevent.i

package libevent

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef void* swig_type_5;
typedef _gostring_ swig_type_6;
typedef void* swig_type_7;
typedef void* swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef void* swig_type_15;
typedef _gostring_ swig_type_16;
typedef void* swig_type_17;
typedef void* swig_type_18;
typedef void* swig_type_19;
typedef void* swig_type_20;
typedef void* swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef void* swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef _gostring_ swig_type_36;
typedef _gostring_ swig_type_37;
typedef _gostring_ swig_type_38;
typedef _gostring_ swig_type_39;
typedef _gostring_ swig_type_40;
typedef _gostring_ swig_type_41;
typedef _gostring_ swig_type_42;
typedef _gostring_ swig_type_43;
typedef _gostring_ swig_type_44;
typedef _gostring_ swig_type_45;
typedef _gostring_ swig_type_46;
typedef _gostring_ swig_type_47;
typedef _gostring_ swig_type_48;
typedef _gostring_ swig_type_49;
typedef _gostring_ swig_type_50;
typedef _gostring_ swig_type_51;
typedef _gostring_ swig_type_52;
typedef _gostring_ swig_type_53;
typedef _gostring_ swig_type_54;
typedef _gostring_ swig_type_55;
typedef _gostring_ swig_type_56;
typedef _gostring_ swig_type_57;
typedef _gostring_ swig_type_58;
typedef _gostring_ swig_type_59;
typedef _gostring_ swig_type_60;
typedef _gostring_ swig_type_61;
typedef long long swig_type_62;
typedef _gostring_ swig_type_63;
typedef _gostring_ swig_type_64;
typedef long long swig_type_65;
typedef _gostring_ swig_type_66;
typedef void* swig_type_67;
typedef void* swig_type_68;
typedef void* swig_type_69;
extern void _wrap_Swig_free_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_libevent_f475800292a41471(swig_intgo arg1);
extern uintptr_t _wrap_evhttp_new_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_evhttp_bind_socket_libevent_f475800292a41471(uintptr_t arg1, swig_type_1 arg2, uintptr_t arg3);
extern uintptr_t _wrap_evhttp_bind_socket_with_handle_libevent_f475800292a41471(uintptr_t arg1, swig_type_2 arg2, uintptr_t arg3);
extern swig_intgo _wrap_evhttp_accept_socket_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_evhttp_accept_socket_with_handle_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_evhttp_bind_listener_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_evhttp_bound_socket_get_listener_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_evhttp_foreach_bound_socket_libevent_f475800292a41471(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern void _wrap_evhttp_del_accept_socket_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_evhttp_bound_socket_get_fd_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_evhttp_free_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_evhttp_set_max_headers_size_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_evhttp_set_max_body_size_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_evhttp_set_default_content_type_libevent_f475800292a41471(uintptr_t arg1, swig_type_3 arg2);
extern void _wrap_evhttp_set_allowed_methods_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_evhttp_set_cb_libevent_f475800292a41471(uintptr_t arg1, swig_type_4 arg2, swig_type_5 arg3, uintptr_t arg4);
extern swig_intgo _wrap_evhttp_del_cb_libevent_f475800292a41471(uintptr_t arg1, swig_type_6 arg2);
extern void _wrap_evhttp_set_gencb_libevent_f475800292a41471(uintptr_t arg1, swig_type_7 arg2, uintptr_t arg3);
extern void _wrap_evhttp_set_bevcb_libevent_f475800292a41471(uintptr_t arg1, swig_type_8 arg2, uintptr_t arg3);
extern swig_intgo _wrap_evhttp_add_virtual_host_libevent_f475800292a41471(uintptr_t arg1, swig_type_9 arg2, uintptr_t arg3);
extern swig_intgo _wrap_evhttp_remove_virtual_host_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_evhttp_add_server_alias_libevent_f475800292a41471(uintptr_t arg1, swig_type_10 arg2);
extern swig_intgo _wrap_evhttp_remove_server_alias_libevent_f475800292a41471(uintptr_t arg1, swig_type_11 arg2);
extern void _wrap_evhttp_set_timeout_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_evhttp_set_timeout_tv_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_evhttp_set_flags_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_evhttp_send_error_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2, swig_type_12 arg3);
extern void _wrap_evhttp_send_reply_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2, swig_type_13 arg3, uintptr_t arg4);
extern void _wrap_evhttp_send_reply_start_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2, swig_type_14 arg3);
extern void _wrap_evhttp_send_reply_chunk_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_evhttp_send_reply_chunk_with_cb_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, swig_type_15 arg3, uintptr_t arg4);
extern void _wrap_evhttp_send_reply_end_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_EVHTTP_REQ_GET_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQ_POST_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQ_HEAD_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQ_PUT_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQ_DELETE_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQ_OPTIONS_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQ_TRACE_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQ_CONNECT_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQ_PATCH_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_REQUEST_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVHTTP_RESPONSE_libevent_f475800292a41471(void);
extern uintptr_t _wrap_evhttp_connection_base_bufferevent_new_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_type_16 arg4, uintptr_t arg5);
extern uintptr_t _wrap_evhttp_connection_get_bufferevent_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_connection_get_server_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_request_new_libevent_f475800292a41471(swig_type_17 arg1, uintptr_t arg2);
extern void _wrap_evhttp_request_set_chunked_cb_libevent_f475800292a41471(uintptr_t arg1, swig_type_18 arg2);
extern void _wrap_evhttp_request_set_header_cb_libevent_f475800292a41471(uintptr_t arg1, swig_type_19 arg2);
extern swig_intgo _wrap_EVREQ_HTTP_TIMEOUT_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVREQ_HTTP_EOF_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVREQ_HTTP_INVALID_HEADER_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVREQ_HTTP_BUFFER_ERROR_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVREQ_HTTP_REQUEST_CANCEL_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVREQ_HTTP_DATA_TOO_LONG_libevent_f475800292a41471(void);
extern void _wrap_evhttp_request_set_error_cb_libevent_f475800292a41471(uintptr_t arg1, swig_type_20 arg2);
extern void _wrap_evhttp_request_set_on_complete_cb_libevent_f475800292a41471(uintptr_t arg1, swig_type_21 arg2, uintptr_t arg3);
extern void _wrap_evhttp_request_free_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_connection_base_new_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, swig_type_22 arg3, uintptr_t arg4);
extern void _wrap_evhttp_connection_set_family_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_evhttp_connection_set_flags_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_evhttp_request_own_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_evhttp_request_is_owned_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_request_get_connection_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_connection_get_base_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_evhttp_connection_set_max_headers_size_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_evhttp_connection_set_max_body_size_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_evhttp_connection_free_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_evhttp_connection_free_on_completion_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_evhttp_connection_set_local_address_libevent_f475800292a41471(uintptr_t arg1, swig_type_23 arg2);
extern void _wrap_evhttp_connection_set_local_port_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_evhttp_connection_set_timeout_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_evhttp_connection_set_timeout_tv_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_evhttp_connection_set_initial_retry_tv_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_evhttp_connection_set_retries_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_evhttp_connection_set_closecb_libevent_f475800292a41471(uintptr_t arg1, swig_type_24 arg2, uintptr_t arg3);
extern void _wrap_evhttp_connection_get_peer_libevent_f475800292a41471(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern uintptr_t _wrap_evhttp_connection_get_addr_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_evhttp_make_request_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, swig_type_25 arg4);
extern void _wrap_evhttp_cancel_request_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_26 _wrap_evhttp_request_get_uri_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_request_get_evhttp_uri_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_evhttp_request_get_command_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_evhttp_request_get_response_code_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_27 _wrap_evhttp_request_get_response_code_line_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_request_get_input_headers_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_request_get_output_headers_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_request_get_input_buffer_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_evhttp_request_get_output_buffer_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_28 _wrap_evhttp_request_get_host_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_29 _wrap_evhttp_find_header_libevent_f475800292a41471(uintptr_t arg1, swig_type_30 arg2);
extern swig_intgo _wrap_evhttp_remove_header_libevent_f475800292a41471(uintptr_t arg1, swig_type_31 arg2);
extern swig_intgo _wrap_evhttp_add_header_libevent_f475800292a41471(uintptr_t arg1, swig_type_32 arg2, swig_type_33 arg3);
extern void _wrap_evhttp_clear_headers_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_34 _wrap_evhttp_encode_uri_libevent_f475800292a41471(swig_type_35 arg1);
extern swig_type_36 _wrap_evhttp_uriencode_libevent_f475800292a41471(swig_type_37 arg1, uintptr_t arg2, swig_intgo arg3);
extern swig_type_38 _wrap_evhttp_decode_uri_libevent_f475800292a41471(swig_type_39 arg1);
extern swig_type_40 _wrap_evhttp_uridecode_libevent_f475800292a41471(swig_type_41 arg1, swig_intgo arg2, swig_voidp arg3);
extern swig_intgo _wrap_evhttp_parse_query_libevent_f475800292a41471(swig_type_42 arg1, uintptr_t arg2);
extern swig_intgo _wrap_evhttp_parse_query_str_libevent_f475800292a41471(swig_type_43 arg1, uintptr_t arg2);
extern swig_type_44 _wrap_evhttp_htmlescape_libevent_f475800292a41471(swig_type_45 arg1);
extern uintptr_t _wrap_evhttp_uri_new_libevent_f475800292a41471(void);
extern void _wrap_evhttp_uri_set_flags_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_type_46 _wrap_evhttp_uri_get_scheme_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_47 _wrap_evhttp_uri_get_userinfo_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_48 _wrap_evhttp_uri_get_host_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_evhttp_uri_get_port_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_49 _wrap_evhttp_uri_get_path_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_50 _wrap_evhttp_uri_get_query_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_51 _wrap_evhttp_uri_get_fragment_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_evhttp_uri_set_scheme_libevent_f475800292a41471(uintptr_t arg1, swig_type_52 arg2);
extern swig_intgo _wrap_evhttp_uri_set_userinfo_libevent_f475800292a41471(uintptr_t arg1, swig_type_53 arg2);
extern swig_intgo _wrap_evhttp_uri_set_host_libevent_f475800292a41471(uintptr_t arg1, swig_type_54 arg2);
extern swig_intgo _wrap_evhttp_uri_set_port_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_evhttp_uri_set_path_libevent_f475800292a41471(uintptr_t arg1, swig_type_55 arg2);
extern swig_intgo _wrap_evhttp_uri_set_query_libevent_f475800292a41471(uintptr_t arg1, swig_type_56 arg2);
extern swig_intgo _wrap_evhttp_uri_set_fragment_libevent_f475800292a41471(uintptr_t arg1, swig_type_57 arg2);
extern uintptr_t _wrap_evhttp_uri_parse_with_flags_libevent_f475800292a41471(swig_type_58 arg1, swig_intgo arg2);
extern uintptr_t _wrap_evhttp_uri_parse_libevent_f475800292a41471(swig_type_59 arg1);
extern void _wrap_evhttp_uri_free_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_60 _wrap_evhttp_uri_join_libevent_f475800292a41471(uintptr_t arg1, swig_type_61 arg2, swig_type_62 arg3);
extern void _wrap_event_enable_debug_mode_libevent_f475800292a41471(void);
extern void _wrap_event_debug_unassign_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_event_base_new_libevent_f475800292a41471(void);
extern swig_intgo _wrap_event_reinit_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_base_dispatch_libevent_f475800292a41471(uintptr_t arg1);
extern swig_type_63 _wrap_event_base_get_method_libevent_f475800292a41471(uintptr_t arg1);
extern swig_voidp _wrap_event_get_supported_methods_libevent_f475800292a41471(void);
extern swig_intgo _wrap_event_gettime_monotonic_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_event_base_get_num_events_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_event_base_get_max_events_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern uintptr_t _wrap_event_config_new_libevent_f475800292a41471(void);
extern void _wrap_event_config_free_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_config_avoid_method_libevent_f475800292a41471(uintptr_t arg1, swig_type_64 arg2);
extern swig_intgo _wrap_EV_FEATURE_ET_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EV_FEATURE_O1_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EV_FEATURE_FDS_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EV_FEATURE_EARLY_CLOSE_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVENT_BASE_FLAG_NOLOCK_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVENT_BASE_FLAG_IGNORE_ENV_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVENT_BASE_FLAG_STARTUP_IOCP_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVENT_BASE_FLAG_NO_CACHE_TIME_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVENT_BASE_FLAG_EPOLL_USE_CHANGELIST_libevent_f475800292a41471(void);
extern swig_intgo _wrap_EVENT_BASE_FLAG_PRECISE_TIMER_libevent_f475800292a41471(void);
extern swig_intgo _wrap_event_base_get_features_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_config_require_features_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_event_config_set_flag_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_event_config_set_num_cpus_hint_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_event_config_set_max_dispatch_interval_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, swig_intgo arg4);
extern uintptr_t _wrap_event_base_new_with_config_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_event_base_free_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_event_base_free_nofinalize_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_event_set_log_callback_libevent_f475800292a41471(swig_voidp arg1);
extern void _wrap_event_set_fatal_callback_libevent_f475800292a41471(swig_voidp arg1);
extern void _wrap_event_enable_debug_logging_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_base_set_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_event_base_loop_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_event_base_loopexit_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_event_base_loopbreak_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_base_loopcontinue_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_base_got_exit_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_base_got_break_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_event_self_cbarg_libevent_f475800292a41471(void);
extern uintptr_t _wrap_event_new_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, short arg3, swig_voidp arg4, uintptr_t arg5);
extern swig_intgo _wrap_event_assign_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, short arg4, swig_voidp arg5, uintptr_t arg6);
extern void _wrap_event_free_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_finalize_libevent_f475800292a41471(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_event_free_finalize_libevent_f475800292a41471(swig_intgo arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_event_base_once_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, short arg3, swig_voidp arg4, uintptr_t arg5, uintptr_t arg6);
extern swig_intgo _wrap_event_add_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_event_remove_timer_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_del_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_del_noblock_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_del_block_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_event_active_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2, short arg3);
extern swig_intgo _wrap_event_pending_libevent_f475800292a41471(uintptr_t arg1, short arg2, uintptr_t arg3);
extern uintptr_t _wrap_event_base_get_running_event_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_initialized_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_event_get_fd_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_event_get_base_libevent_f475800292a41471(uintptr_t arg1);
extern short _wrap_event_get_events_libevent_f475800292a41471(uintptr_t arg1);
extern swig_voidp _wrap_event_get_callback_libevent_f475800292a41471(uintptr_t arg1);
extern uintptr_t _wrap_event_get_callback_arg_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_get_priority_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_event_get_assignment_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6);
extern swig_type_65 _wrap_event_get_struct_event_size_libevent_f475800292a41471(void);
extern swig_type_66 _wrap_event_get_version_libevent_f475800292a41471(void);
extern uintptr_t _wrap_event_get_version_number_libevent_f475800292a41471(void);
extern swig_intgo _wrap_event_base_priority_init_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_event_base_get_npriorities_libevent_f475800292a41471(uintptr_t arg1);
extern swig_intgo _wrap_event_priority_set_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern uintptr_t _wrap_event_base_init_common_timeout_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_event_set_mem_functions_libevent_f475800292a41471(swig_type_67 arg1, swig_type_68 arg2, swig_type_69 arg3);
extern void _wrap_event_base_dump_events_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_event_base_active_by_fd_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2, short arg3);
extern void _wrap_event_base_active_by_signal_libevent_f475800292a41471(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_event_base_foreach_event_libevent_f475800292a41471(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern swig_intgo _wrap_event_base_gettimeofday_cached_libevent_f475800292a41471(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_event_base_update_cache_time_libevent_f475800292a41471(uintptr_t arg1);
extern void _wrap_libevent_global_shutdown_libevent_f475800292a41471(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_libevent_f475800292a41471(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const HTTP_OK int = 200
const HTTP_NOCONTENT int = 204
const HTTP_MOVEPERM int = 301
const HTTP_MOVETEMP int = 302
const HTTP_NOTMODIFIED int = 304
const HTTP_BADREQUEST int = 400
const HTTP_NOTFOUND int = 404
const HTTP_BADMETHOD int = 405
const HTTP_ENTITYTOOLARGE int = 413
const HTTP_EXPECTATIONFAILED int = 417
const HTTP_INTERNAL int = 500
const HTTP_NOTIMPLEMENTED int = 501
const HTTP_SERVUNAVAIL int = 503
func Evhttp_new(arg1 Struct_SS_event_base) (_swig_ret Struct_SS_evhttp) {
	var swig_r Struct_SS_evhttp
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evhttp)(SwigcptrStruct_SS_evhttp(C._wrap_evhttp_new_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_bind_socket(arg1 Struct_SS_evhttp, arg2 string, arg3 Ev_uint16_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_bind_socket_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_bind_socket_with_handle(arg1 Struct_SS_evhttp, arg2 string, arg3 Ev_uint16_t) (_swig_ret Struct_SS_evhttp_bound_socket) {
	var swig_r Struct_SS_evhttp_bound_socket
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Struct_SS_evhttp_bound_socket)(SwigcptrStruct_SS_evhttp_bound_socket(C._wrap_evhttp_bind_socket_with_handle_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_accept_socket(arg1 Struct_SS_evhttp, arg2 Evutil_socket_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_accept_socket_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Evhttp_accept_socket_with_handle(arg1 Struct_SS_evhttp, arg2 Evutil_socket_t) (_swig_ret Struct_SS_evhttp_bound_socket) {
	var swig_r Struct_SS_evhttp_bound_socket
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Struct_SS_evhttp_bound_socket)(SwigcptrStruct_SS_evhttp_bound_socket(C._wrap_evhttp_accept_socket_with_handle_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Evhttp_bind_listener(arg1 Struct_SS_evhttp, arg2 Struct_SS_evconnlistener) (_swig_ret Struct_SS_evhttp_bound_socket) {
	var swig_r Struct_SS_evhttp_bound_socket
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Struct_SS_evhttp_bound_socket)(SwigcptrStruct_SS_evhttp_bound_socket(C._wrap_evhttp_bind_listener_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Evhttp_bound_socket_get_listener(arg1 Struct_SS_evhttp_bound_socket) (_swig_ret Struct_SS_evconnlistener) {
	var swig_r Struct_SS_evconnlistener
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evconnlistener)(SwigcptrStruct_SS_evconnlistener(C._wrap_evhttp_bound_socket_get_listener_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_foreach_bound_socket(arg1 Struct_SS_evhttp, arg2 *_swig_fnptr, arg3 uintptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_evhttp_foreach_bound_socket_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Evhttp_del_accept_socket(arg1 Struct_SS_evhttp, arg2 Struct_SS_evhttp_bound_socket) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_del_accept_socket_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_bound_socket_get_fd(arg1 Struct_SS_evhttp_bound_socket) (_swig_ret Evutil_socket_t) {
	var swig_r Evutil_socket_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Evutil_socket_t)(SwigcptrEvutil_socket_t(C._wrap_evhttp_bound_socket_get_fd_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_free(arg1 Struct_SS_evhttp) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_free_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Evhttp_set_max_headers_size(arg1 Struct_SS_evhttp, arg2 Ev_ssize_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_set_max_headers_size_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_set_max_body_size(arg1 Struct_SS_evhttp, arg2 Ev_ssize_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_set_max_body_size_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_set_default_content_type(arg1 Struct_SS_evhttp, arg2 string) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_set_default_content_type_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Evhttp_set_allowed_methods(arg1 Struct_SS_evhttp, arg2 Ev_uint16_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_set_allowed_methods_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_set_cb(arg1 Struct_SS_evhttp, arg2 string, arg3 _swig_fnptr, arg4 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_evhttp_set_cb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)), C.swig_type_5(_swig_i_2), C.uintptr_t(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_del_cb(arg1 Struct_SS_evhttp, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_del_cb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_set_gencb(arg1 Struct_SS_evhttp, arg2 _swig_fnptr, arg3 uintptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_evhttp_set_gencb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_type_7(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Evhttp_set_bevcb(arg1 Struct_SS_evhttp, arg2 _swig_fnptr, arg3 uintptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_evhttp_set_bevcb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Evhttp_add_virtual_host(arg1 Struct_SS_evhttp, arg2 string, arg3 Struct_SS_evhttp) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_add_virtual_host_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_remove_virtual_host(arg1 Struct_SS_evhttp, arg2 Struct_SS_evhttp) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_remove_virtual_host_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Evhttp_add_server_alias(arg1 Struct_SS_evhttp, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_add_server_alias_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_remove_server_alias(arg1 Struct_SS_evhttp, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_remove_server_alias_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_set_timeout(arg1 Struct_SS_evhttp, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_set_timeout_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Evhttp_set_timeout_tv(arg1 Struct_SS_evhttp, arg2 Struct_SS_timeval) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_set_timeout_tv_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

const EVHTTP_SERVER_LINGERING_CLOSE int = 0x0001
func Evhttp_set_flags(arg1 Struct_SS_evhttp, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_set_flags_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Evhttp_send_error(arg1 Struct_SS_evhttp_request, arg2 int, arg3 string) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_evhttp_send_error_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func Evhttp_send_reply(arg1 Struct_SS_evhttp_request, arg2 int, arg3 string, arg4 Struct_SS_evbuffer) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_evhttp_send_reply_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_2)), C.uintptr_t(_swig_i_3))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func Evhttp_send_reply_start(arg1 Struct_SS_evhttp_request, arg2 int, arg3 string) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_evhttp_send_reply_start_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func Evhttp_send_reply_chunk(arg1 Struct_SS_evhttp_request, arg2 Struct_SS_evbuffer) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_send_reply_chunk_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_send_reply_chunk_with_cb(arg1 Struct_SS_evhttp_request, arg2 Struct_SS_evbuffer, arg3 _swig_fnptr, arg4 uintptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_evhttp_send_reply_chunk_with_cb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_type_15(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func Evhttp_send_reply_end(arg1 Struct_SS_evhttp_request) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_send_reply_end_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

type Enum_SS_evhttp_cmd_type int
func _swig_getEVHTTP_REQ_GET() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_GET_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_GET Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_GET()
func _swig_getEVHTTP_REQ_POST() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_POST_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_POST Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_POST()
func _swig_getEVHTTP_REQ_HEAD() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_HEAD_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_HEAD Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_HEAD()
func _swig_getEVHTTP_REQ_PUT() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_PUT_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_PUT Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_PUT()
func _swig_getEVHTTP_REQ_DELETE() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_DELETE_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_DELETE Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_DELETE()
func _swig_getEVHTTP_REQ_OPTIONS() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_OPTIONS_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_OPTIONS Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_OPTIONS()
func _swig_getEVHTTP_REQ_TRACE() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_TRACE_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_TRACE Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_TRACE()
func _swig_getEVHTTP_REQ_CONNECT() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_CONNECT_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_CONNECT Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_CONNECT()
func _swig_getEVHTTP_REQ_PATCH() (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_EVHTTP_REQ_PATCH_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQ_PATCH Enum_SS_evhttp_cmd_type = _swig_getEVHTTP_REQ_PATCH()
type Enum_SS_evhttp_request_kind int
func _swig_getEVHTTP_REQUEST() (_swig_ret Enum_SS_evhttp_request_kind) {
	var swig_r Enum_SS_evhttp_request_kind
	swig_r = (Enum_SS_evhttp_request_kind)(C._wrap_EVHTTP_REQUEST_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_REQUEST Enum_SS_evhttp_request_kind = _swig_getEVHTTP_REQUEST()
func _swig_getEVHTTP_RESPONSE() (_swig_ret Enum_SS_evhttp_request_kind) {
	var swig_r Enum_SS_evhttp_request_kind
	swig_r = (Enum_SS_evhttp_request_kind)(C._wrap_EVHTTP_RESPONSE_libevent_f475800292a41471())
	return swig_r
}

var EVHTTP_RESPONSE Enum_SS_evhttp_request_kind = _swig_getEVHTTP_RESPONSE()
func Evhttp_connection_base_bufferevent_new(arg1 Struct_SS_event_base, arg2 Struct_SS_evdns_base, arg3 Struct_SS_bufferevent, arg4 string, arg5 Ev_uint16_t) (_swig_ret Struct_SS_evhttp_connection) {
	var swig_r Struct_SS_evhttp_connection
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5.Swigcptr()
	swig_r = (Struct_SS_evhttp_connection)(SwigcptrStruct_SS_evhttp_connection(C._wrap_evhttp_connection_base_bufferevent_new_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), *(*C.swig_type_16)(unsafe.Pointer(&_swig_i_3)), C.uintptr_t(_swig_i_4))))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func Evhttp_connection_get_bufferevent(arg1 Struct_SS_evhttp_connection) (_swig_ret Struct_SS_bufferevent) {
	var swig_r Struct_SS_bufferevent
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_bufferevent)(SwigcptrStruct_SS_bufferevent(C._wrap_evhttp_connection_get_bufferevent_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_connection_get_server(arg1 Struct_SS_evhttp_connection) (_swig_ret Struct_SS_evhttp) {
	var swig_r Struct_SS_evhttp
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evhttp)(SwigcptrStruct_SS_evhttp(C._wrap_evhttp_connection_get_server_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_request_new(arg1 _swig_fnptr, arg2 uintptr) (_swig_ret Struct_SS_evhttp_request) {
	var swig_r Struct_SS_evhttp_request
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Struct_SS_evhttp_request)(SwigcptrStruct_SS_evhttp_request(C._wrap_evhttp_request_new_libevent_f475800292a41471(C.swig_type_17(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Evhttp_request_set_chunked_cb(arg1 Struct_SS_evhttp_request, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_request_set_chunked_cb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_type_18(_swig_i_1))
}

func Evhttp_request_set_header_cb(arg1 Struct_SS_evhttp_request, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_request_set_header_cb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_type_19(_swig_i_1))
}

type Enum_SS_evhttp_request_error int
func _swig_getEVREQ_HTTP_TIMEOUT() (_swig_ret Enum_SS_evhttp_request_error) {
	var swig_r Enum_SS_evhttp_request_error
	swig_r = (Enum_SS_evhttp_request_error)(C._wrap_EVREQ_HTTP_TIMEOUT_libevent_f475800292a41471())
	return swig_r
}

var EVREQ_HTTP_TIMEOUT Enum_SS_evhttp_request_error = _swig_getEVREQ_HTTP_TIMEOUT()
func _swig_getEVREQ_HTTP_EOF() (_swig_ret Enum_SS_evhttp_request_error) {
	var swig_r Enum_SS_evhttp_request_error
	swig_r = (Enum_SS_evhttp_request_error)(C._wrap_EVREQ_HTTP_EOF_libevent_f475800292a41471())
	return swig_r
}

var EVREQ_HTTP_EOF Enum_SS_evhttp_request_error = _swig_getEVREQ_HTTP_EOF()
func _swig_getEVREQ_HTTP_INVALID_HEADER() (_swig_ret Enum_SS_evhttp_request_error) {
	var swig_r Enum_SS_evhttp_request_error
	swig_r = (Enum_SS_evhttp_request_error)(C._wrap_EVREQ_HTTP_INVALID_HEADER_libevent_f475800292a41471())
	return swig_r
}

var EVREQ_HTTP_INVALID_HEADER Enum_SS_evhttp_request_error = _swig_getEVREQ_HTTP_INVALID_HEADER()
func _swig_getEVREQ_HTTP_BUFFER_ERROR() (_swig_ret Enum_SS_evhttp_request_error) {
	var swig_r Enum_SS_evhttp_request_error
	swig_r = (Enum_SS_evhttp_request_error)(C._wrap_EVREQ_HTTP_BUFFER_ERROR_libevent_f475800292a41471())
	return swig_r
}

var EVREQ_HTTP_BUFFER_ERROR Enum_SS_evhttp_request_error = _swig_getEVREQ_HTTP_BUFFER_ERROR()
func _swig_getEVREQ_HTTP_REQUEST_CANCEL() (_swig_ret Enum_SS_evhttp_request_error) {
	var swig_r Enum_SS_evhttp_request_error
	swig_r = (Enum_SS_evhttp_request_error)(C._wrap_EVREQ_HTTP_REQUEST_CANCEL_libevent_f475800292a41471())
	return swig_r
}

var EVREQ_HTTP_REQUEST_CANCEL Enum_SS_evhttp_request_error = _swig_getEVREQ_HTTP_REQUEST_CANCEL()
func _swig_getEVREQ_HTTP_DATA_TOO_LONG() (_swig_ret Enum_SS_evhttp_request_error) {
	var swig_r Enum_SS_evhttp_request_error
	swig_r = (Enum_SS_evhttp_request_error)(C._wrap_EVREQ_HTTP_DATA_TOO_LONG_libevent_f475800292a41471())
	return swig_r
}

var EVREQ_HTTP_DATA_TOO_LONG Enum_SS_evhttp_request_error = _swig_getEVREQ_HTTP_DATA_TOO_LONG()
func Evhttp_request_set_error_cb(arg1 Struct_SS_evhttp_request, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_request_set_error_cb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_type_20(_swig_i_1))
}

func Evhttp_request_set_on_complete_cb(arg1 Struct_SS_evhttp_request, arg2 _swig_fnptr, arg3 uintptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_evhttp_request_set_on_complete_cb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_type_21(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Evhttp_request_free(arg1 Struct_SS_evhttp_request) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_request_free_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Evhttp_connection_base_new(arg1 Struct_SS_event_base, arg2 Struct_SS_evdns_base, arg3 string, arg4 Ev_uint16_t) (_swig_ret Struct_SS_evhttp_connection) {
	var swig_r Struct_SS_evhttp_connection
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Struct_SS_evhttp_connection)(SwigcptrStruct_SS_evhttp_connection(C._wrap_evhttp_connection_base_new_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_2)), C.uintptr_t(_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Evhttp_connection_set_family(arg1 Struct_SS_evhttp_connection, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_connection_set_family_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

const EVHTTP_CON_REUSE_CONNECTED_ADDR int = 0x0008
const EVHTTP_CON_READ_ON_WRITE_ERROR int = 0x0010
const EVHTTP_CON_LINGERING_CLOSE int = 0x0020
const EVHTTP_CON_PUBLIC_FLAGS_END int = 0x100000
func Evhttp_connection_set_flags(arg1 Struct_SS_evhttp_connection, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_connection_set_flags_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Evhttp_request_own(arg1 Struct_SS_evhttp_request) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_request_own_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Evhttp_request_is_owned(arg1 Struct_SS_evhttp_request) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_request_is_owned_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Evhttp_request_get_connection(arg1 Struct_SS_evhttp_request) (_swig_ret Struct_SS_evhttp_connection) {
	var swig_r Struct_SS_evhttp_connection
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evhttp_connection)(SwigcptrStruct_SS_evhttp_connection(C._wrap_evhttp_request_get_connection_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_connection_get_base(arg1 Struct_SS_evhttp_connection) (_swig_ret Struct_SS_event_base) {
	var swig_r Struct_SS_event_base
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_event_base)(SwigcptrStruct_SS_event_base(C._wrap_evhttp_connection_get_base_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_connection_set_max_headers_size(arg1 Struct_SS_evhttp_connection, arg2 Ev_ssize_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_connection_set_max_headers_size_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_connection_set_max_body_size(arg1 Struct_SS_evhttp_connection, arg2 Ev_ssize_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_connection_set_max_body_size_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_connection_free(arg1 Struct_SS_evhttp_connection) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_connection_free_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Evhttp_connection_free_on_completion(arg1 Struct_SS_evhttp_connection) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_connection_free_on_completion_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Evhttp_connection_set_local_address(arg1 Struct_SS_evhttp_connection, arg2 string) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_connection_set_local_address_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_23)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Evhttp_connection_set_local_port(arg1 Struct_SS_evhttp_connection, arg2 Ev_uint16_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_connection_set_local_port_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_connection_set_timeout(arg1 Struct_SS_evhttp_connection, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_connection_set_timeout_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Evhttp_connection_set_timeout_tv(arg1 Struct_SS_evhttp_connection, arg2 Struct_SS_timeval) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_connection_set_timeout_tv_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_connection_set_initial_retry_tv(arg1 Struct_SS_evhttp_connection, arg2 Struct_SS_timeval) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_evhttp_connection_set_initial_retry_tv_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Evhttp_connection_set_retries(arg1 Struct_SS_evhttp_connection, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_connection_set_retries_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Evhttp_connection_set_closecb(arg1 Struct_SS_evhttp_connection, arg2 _swig_fnptr, arg3 uintptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_evhttp_connection_set_closecb_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_type_24(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Evhttp_connection_get_peer(arg1 Struct_SS_evhttp_connection, arg2 *string, arg3 Ev_uint16_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_evhttp_connection_get_peer_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Evhttp_connection_get_addr(arg1 Struct_SS_evhttp_connection) (_swig_ret Struct_SS_sockaddr) {
	var swig_r Struct_SS_sockaddr
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_sockaddr)(SwigcptrStruct_SS_sockaddr(C._wrap_evhttp_connection_get_addr_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_make_request(arg1 Struct_SS_evhttp_connection, arg2 Struct_SS_evhttp_request, arg3 Enum_SS_evhttp_cmd_type, arg4 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_evhttp_make_request_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), *(*C.swig_type_25)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func Evhttp_cancel_request(arg1 Struct_SS_evhttp_request) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_cancel_request_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Evhttp_request_get_uri(arg1 Struct_SS_evhttp_request) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_request_get_uri_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_request_get_evhttp_uri(arg1 Struct_SS_evhttp_request) (_swig_ret Struct_SS_evhttp_uri) {
	var swig_r Struct_SS_evhttp_uri
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evhttp_uri)(SwigcptrStruct_SS_evhttp_uri(C._wrap_evhttp_request_get_evhttp_uri_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_request_get_command(arg1 Struct_SS_evhttp_request) (_swig_ret Enum_SS_evhttp_cmd_type) {
	var swig_r Enum_SS_evhttp_cmd_type
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Enum_SS_evhttp_cmd_type)(C._wrap_evhttp_request_get_command_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Evhttp_request_get_response_code(arg1 Struct_SS_evhttp_request) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_request_get_response_code_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Evhttp_request_get_response_code_line(arg1 Struct_SS_evhttp_request) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_request_get_response_code_line_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_request_get_input_headers(arg1 Struct_SS_evhttp_request) (_swig_ret Struct_SS_evkeyvalq) {
	var swig_r Struct_SS_evkeyvalq
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evkeyvalq)(SwigcptrStruct_SS_evkeyvalq(C._wrap_evhttp_request_get_input_headers_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_request_get_output_headers(arg1 Struct_SS_evhttp_request) (_swig_ret Struct_SS_evkeyvalq) {
	var swig_r Struct_SS_evkeyvalq
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evkeyvalq)(SwigcptrStruct_SS_evkeyvalq(C._wrap_evhttp_request_get_output_headers_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_request_get_input_buffer(arg1 Struct_SS_evhttp_request) (_swig_ret Struct_SS_evbuffer) {
	var swig_r Struct_SS_evbuffer
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evbuffer)(SwigcptrStruct_SS_evbuffer(C._wrap_evhttp_request_get_input_buffer_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_request_get_output_buffer(arg1 Struct_SS_evhttp_request) (_swig_ret Struct_SS_evbuffer) {
	var swig_r Struct_SS_evbuffer
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_evbuffer)(SwigcptrStruct_SS_evbuffer(C._wrap_evhttp_request_get_output_buffer_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Evhttp_request_get_host(arg1 Struct_SS_evhttp_request) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_request_get_host_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_find_header(arg1 Struct_SS_evkeyvalq, arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r_p := C._wrap_evhttp_find_header_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_30)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_remove_header(arg1 Struct_SS_evkeyvalq, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_remove_header_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_31)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_add_header(arg1 Struct_SS_evkeyvalq, arg2 string, arg3 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_evhttp_add_header_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_32)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_33)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Evhttp_clear_headers(arg1 Struct_SS_evkeyvalq) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_clear_headers_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Evhttp_encode_uri(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_evhttp_encode_uri_libevent_f475800292a41471(*(*C.swig_type_35)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uriencode(arg1 string, arg2 Ev_ssize_t, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r_p := C._wrap_evhttp_uriencode_libevent_f475800292a41471(*(*C.swig_type_37)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_decode_uri(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_evhttp_decode_uri_libevent_f475800292a41471(*(*C.swig_type_39)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uridecode(arg1 string, arg2 int, arg3 *int64) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_evhttp_uridecode_libevent_f475800292a41471(*(*C.swig_type_41)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1), C.swig_voidp(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_parse_query(arg1 string, arg2 Struct_SS_evkeyvalq) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_parse_query_libevent_f475800292a41471(*(*C.swig_type_42)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Evhttp_parse_query_str(arg1 string, arg2 Struct_SS_evkeyvalq) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_parse_query_str_libevent_f475800292a41471(*(*C.swig_type_43)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Evhttp_htmlescape(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_evhttp_htmlescape_libevent_f475800292a41471(*(*C.swig_type_45)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uri_new() (_swig_ret Struct_SS_evhttp_uri) {
	var swig_r Struct_SS_evhttp_uri
	swig_r = (Struct_SS_evhttp_uri)(SwigcptrStruct_SS_evhttp_uri(C._wrap_evhttp_uri_new_libevent_f475800292a41471()))
	return swig_r
}

func Evhttp_uri_set_flags(arg1 Struct_SS_evhttp_uri, arg2 uint) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_evhttp_uri_set_flags_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Evhttp_uri_get_scheme(arg1 Struct_SS_evhttp_uri) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_uri_get_scheme_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uri_get_userinfo(arg1 Struct_SS_evhttp_uri) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_uri_get_userinfo_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uri_get_host(arg1 Struct_SS_evhttp_uri) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_uri_get_host_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uri_get_port(arg1 Struct_SS_evhttp_uri) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_evhttp_uri_get_port_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Evhttp_uri_get_path(arg1 Struct_SS_evhttp_uri) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_uri_get_path_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uri_get_query(arg1 Struct_SS_evhttp_uri) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_uri_get_query_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uri_get_fragment(arg1 Struct_SS_evhttp_uri) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_evhttp_uri_get_fragment_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Evhttp_uri_set_scheme(arg1 Struct_SS_evhttp_uri, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_uri_set_scheme_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_52)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_uri_set_userinfo(arg1 Struct_SS_evhttp_uri, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_uri_set_userinfo_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_53)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_uri_set_host(arg1 Struct_SS_evhttp_uri, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_uri_set_host_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_54)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_uri_set_port(arg1 Struct_SS_evhttp_uri, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_uri_set_port_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Evhttp_uri_set_path(arg1 Struct_SS_evhttp_uri, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_uri_set_path_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_55)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_uri_set_query(arg1 Struct_SS_evhttp_uri, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_uri_set_query_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_56)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_uri_set_fragment(arg1 Struct_SS_evhttp_uri, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_evhttp_uri_set_fragment_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_57)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Evhttp_uri_parse_with_flags(arg1 string, arg2 uint) (_swig_ret Struct_SS_evhttp_uri) {
	var swig_r Struct_SS_evhttp_uri
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Struct_SS_evhttp_uri)(SwigcptrStruct_SS_evhttp_uri(C._wrap_evhttp_uri_parse_with_flags_libevent_f475800292a41471(*(*C.swig_type_58)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

const EVHTTP_URI_NONCONFORMANT int = 0x01
func Evhttp_uri_parse(arg1 string) (_swig_ret Struct_SS_evhttp_uri) {
	var swig_r Struct_SS_evhttp_uri
	_swig_i_0 := arg1
	swig_r = (Struct_SS_evhttp_uri)(SwigcptrStruct_SS_evhttp_uri(C._wrap_evhttp_uri_parse_libevent_f475800292a41471(*(*C.swig_type_59)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Evhttp_uri_free(arg1 Struct_SS_evhttp_uri) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_evhttp_uri_free_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Evhttp_uri_join(arg1 Struct_SS_evhttp_uri, arg2 string, arg3 int64) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_evhttp_uri_join_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_61)(unsafe.Pointer(&_swig_i_1)), C.swig_type_62(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Event_enable_debug_mode() {
	C._wrap_event_enable_debug_mode_libevent_f475800292a41471()
}

func Event_debug_unassign(arg1 Struct_SS_event) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_event_debug_unassign_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Event_base_new() (_swig_ret Struct_SS_event_base) {
	var swig_r Struct_SS_event_base
	swig_r = (Struct_SS_event_base)(SwigcptrStruct_SS_event_base(C._wrap_event_base_new_libevent_f475800292a41471()))
	return swig_r
}

func Event_reinit(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_reinit_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_base_dispatch(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_base_dispatch_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_base_get_method(arg1 Struct_SS_event_base) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_event_base_get_method_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Event_get_supported_methods() (_swig_ret *string) {
	var swig_r *string
	swig_r = (*string)(C._wrap_event_get_supported_methods_libevent_f475800292a41471())
	return swig_r
}

func Event_gettime_monotonic(arg1 Struct_SS_event_base, arg2 Struct_SS_timeval) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_event_gettime_monotonic_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

const EVENT_BASE_COUNT_ACTIVE uint = 1
const EVENT_BASE_COUNT_VIRTUAL uint = 2
const EVENT_BASE_COUNT_ADDED uint = 4
func Event_base_get_num_events(arg1 Struct_SS_event_base, arg2 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_event_base_get_num_events_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Event_base_get_max_events(arg1 Struct_SS_event_base, arg2 uint, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_event_base_get_max_events_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Event_config_new() (_swig_ret Struct_SS_event_config) {
	var swig_r Struct_SS_event_config
	swig_r = (Struct_SS_event_config)(SwigcptrStruct_SS_event_config(C._wrap_event_config_new_libevent_f475800292a41471()))
	return swig_r
}

func Event_config_free(arg1 Struct_SS_event_config) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_event_config_free_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Event_config_avoid_method(arg1 Struct_SS_event_config, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_event_config_avoid_method_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), *(*C.swig_type_64)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

type Enum_SS_event_method_feature int
func _swig_getEV_FEATURE_ET() (_swig_ret Enum_SS_event_method_feature) {
	var swig_r Enum_SS_event_method_feature
	swig_r = (Enum_SS_event_method_feature)(C._wrap_EV_FEATURE_ET_libevent_f475800292a41471())
	return swig_r
}

var EV_FEATURE_ET Enum_SS_event_method_feature = _swig_getEV_FEATURE_ET()
func _swig_getEV_FEATURE_O1() (_swig_ret Enum_SS_event_method_feature) {
	var swig_r Enum_SS_event_method_feature
	swig_r = (Enum_SS_event_method_feature)(C._wrap_EV_FEATURE_O1_libevent_f475800292a41471())
	return swig_r
}

var EV_FEATURE_O1 Enum_SS_event_method_feature = _swig_getEV_FEATURE_O1()
func _swig_getEV_FEATURE_FDS() (_swig_ret Enum_SS_event_method_feature) {
	var swig_r Enum_SS_event_method_feature
	swig_r = (Enum_SS_event_method_feature)(C._wrap_EV_FEATURE_FDS_libevent_f475800292a41471())
	return swig_r
}

var EV_FEATURE_FDS Enum_SS_event_method_feature = _swig_getEV_FEATURE_FDS()
func _swig_getEV_FEATURE_EARLY_CLOSE() (_swig_ret Enum_SS_event_method_feature) {
	var swig_r Enum_SS_event_method_feature
	swig_r = (Enum_SS_event_method_feature)(C._wrap_EV_FEATURE_EARLY_CLOSE_libevent_f475800292a41471())
	return swig_r
}

var EV_FEATURE_EARLY_CLOSE Enum_SS_event_method_feature = _swig_getEV_FEATURE_EARLY_CLOSE()
type Enum_SS_event_base_config_flag int
func _swig_getEVENT_BASE_FLAG_NOLOCK() (_swig_ret Enum_SS_event_base_config_flag) {
	var swig_r Enum_SS_event_base_config_flag
	swig_r = (Enum_SS_event_base_config_flag)(C._wrap_EVENT_BASE_FLAG_NOLOCK_libevent_f475800292a41471())
	return swig_r
}

var EVENT_BASE_FLAG_NOLOCK Enum_SS_event_base_config_flag = _swig_getEVENT_BASE_FLAG_NOLOCK()
func _swig_getEVENT_BASE_FLAG_IGNORE_ENV() (_swig_ret Enum_SS_event_base_config_flag) {
	var swig_r Enum_SS_event_base_config_flag
	swig_r = (Enum_SS_event_base_config_flag)(C._wrap_EVENT_BASE_FLAG_IGNORE_ENV_libevent_f475800292a41471())
	return swig_r
}

var EVENT_BASE_FLAG_IGNORE_ENV Enum_SS_event_base_config_flag = _swig_getEVENT_BASE_FLAG_IGNORE_ENV()
func _swig_getEVENT_BASE_FLAG_STARTUP_IOCP() (_swig_ret Enum_SS_event_base_config_flag) {
	var swig_r Enum_SS_event_base_config_flag
	swig_r = (Enum_SS_event_base_config_flag)(C._wrap_EVENT_BASE_FLAG_STARTUP_IOCP_libevent_f475800292a41471())
	return swig_r
}

var EVENT_BASE_FLAG_STARTUP_IOCP Enum_SS_event_base_config_flag = _swig_getEVENT_BASE_FLAG_STARTUP_IOCP()
func _swig_getEVENT_BASE_FLAG_NO_CACHE_TIME() (_swig_ret Enum_SS_event_base_config_flag) {
	var swig_r Enum_SS_event_base_config_flag
	swig_r = (Enum_SS_event_base_config_flag)(C._wrap_EVENT_BASE_FLAG_NO_CACHE_TIME_libevent_f475800292a41471())
	return swig_r
}

var EVENT_BASE_FLAG_NO_CACHE_TIME Enum_SS_event_base_config_flag = _swig_getEVENT_BASE_FLAG_NO_CACHE_TIME()
func _swig_getEVENT_BASE_FLAG_EPOLL_USE_CHANGELIST() (_swig_ret Enum_SS_event_base_config_flag) {
	var swig_r Enum_SS_event_base_config_flag
	swig_r = (Enum_SS_event_base_config_flag)(C._wrap_EVENT_BASE_FLAG_EPOLL_USE_CHANGELIST_libevent_f475800292a41471())
	return swig_r
}

var EVENT_BASE_FLAG_EPOLL_USE_CHANGELIST Enum_SS_event_base_config_flag = _swig_getEVENT_BASE_FLAG_EPOLL_USE_CHANGELIST()
func _swig_getEVENT_BASE_FLAG_PRECISE_TIMER() (_swig_ret Enum_SS_event_base_config_flag) {
	var swig_r Enum_SS_event_base_config_flag
	swig_r = (Enum_SS_event_base_config_flag)(C._wrap_EVENT_BASE_FLAG_PRECISE_TIMER_libevent_f475800292a41471())
	return swig_r
}

var EVENT_BASE_FLAG_PRECISE_TIMER Enum_SS_event_base_config_flag = _swig_getEVENT_BASE_FLAG_PRECISE_TIMER()
func Event_base_get_features(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_base_get_features_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_config_require_features(arg1 Struct_SS_event_config, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_event_config_require_features_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Event_config_set_flag(arg1 Struct_SS_event_config, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_event_config_set_flag_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Event_config_set_num_cpus_hint(arg1 Struct_SS_event_config, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_event_config_set_num_cpus_hint_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Event_config_set_max_dispatch_interval(arg1 Struct_SS_event_config, arg2 Struct_SS_timeval, arg3 int, arg4 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_event_config_set_max_dispatch_interval_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3)))
	return swig_r
}

func Event_base_new_with_config(arg1 Struct_SS_event_config) (_swig_ret Struct_SS_event_base) {
	var swig_r Struct_SS_event_base
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_event_base)(SwigcptrStruct_SS_event_base(C._wrap_event_base_new_with_config_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Event_base_free(arg1 Struct_SS_event_base) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_event_base_free_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Event_base_free_nofinalize(arg1 Struct_SS_event_base) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_event_base_free_nofinalize_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

const EVENT_LOG_DEBUG int = 0
const EVENT_LOG_MSG int = 1
const EVENT_LOG_WARN int = 2
const EVENT_LOG_ERR int = 3
const X_EVENT_LOG_DEBUG int = 0
const X_EVENT_LOG_MSG int = 1
const X_EVENT_LOG_WARN int = 2
const X_EVENT_LOG_ERR int = 3
func Event_set_log_callback(arg1 *_swig_fnptr) {
	_swig_i_0 := arg1
	C._wrap_event_set_log_callback_libevent_f475800292a41471(C.swig_voidp(_swig_i_0))
}

func Event_set_fatal_callback(arg1 *_swig_fnptr) {
	_swig_i_0 := arg1
	C._wrap_event_set_fatal_callback_libevent_f475800292a41471(C.swig_voidp(_swig_i_0))
}

const EVENT_DBG_ALL uint = 0xffffffff
const EVENT_DBG_NONE int = 0
func Event_enable_debug_logging(arg1 Ev_uint32_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_event_enable_debug_logging_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Event_base_set(arg1 Struct_SS_event_base, arg2 Struct_SS_event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_event_base_set_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

const EVLOOP_ONCE int = 0x01
const EVLOOP_NONBLOCK int = 0x02
const EVLOOP_NO_EXIT_ON_EMPTY int = 0x04
func Event_base_loop(arg1 Struct_SS_event_base, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_event_base_loop_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Event_base_loopexit(arg1 Struct_SS_event_base, arg2 Struct_SS_timeval) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_event_base_loopexit_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Event_base_loopbreak(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_base_loopbreak_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_base_loopcontinue(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_base_loopcontinue_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_base_got_exit(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_base_got_exit_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_base_got_break(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_base_got_break_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

const EV_TIMEOUT int = 0x01
const EV_READ int = 0x02
const EV_WRITE int = 0x04
const EV_SIGNAL int = 0x08
const EV_PERSIST int = 0x10
const EV_ET int = 0x20
const EV_FINALIZE int = 0x40
const EV_CLOSED int = 0x80
func Event_self_cbarg() (_swig_ret uintptr) {
	var swig_r uintptr
	swig_r = (uintptr)(C._wrap_event_self_cbarg_libevent_f475800292a41471())
	return swig_r
}

func Event_new(arg1 Struct_SS_event_base, arg2 Evutil_socket_t, arg3 int16, arg4 *_swig_fnptr, arg5 uintptr) (_swig_ret Struct_SS_event) {
	var swig_r Struct_SS_event
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (Struct_SS_event)(SwigcptrStruct_SS_event(C._wrap_event_new_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3), C.uintptr_t(_swig_i_4))))
	return swig_r
}

func Event_assign(arg1 Struct_SS_event, arg2 Struct_SS_event_base, arg3 Evutil_socket_t, arg4 int16, arg5 *_swig_fnptr, arg6 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_event_assign_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.short(_swig_i_3), C.swig_voidp(_swig_i_4), C.uintptr_t(_swig_i_5)))
	return swig_r
}

func Event_free(arg1 Struct_SS_event) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_event_free_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))
}

func Event_finalize(arg1 uint, arg2 Struct_SS_event, arg3 *_swig_fnptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_event_finalize_libevent_f475800292a41471(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func Event_free_finalize(arg1 uint, arg2 Struct_SS_event, arg3 *_swig_fnptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_event_free_finalize_libevent_f475800292a41471(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func Event_base_once(arg1 Struct_SS_event_base, arg2 Evutil_socket_t, arg3 int16, arg4 *_swig_fnptr, arg5 uintptr, arg6 Struct_SS_timeval) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	swig_r = (int)(C._wrap_event_base_once_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3), C.uintptr_t(_swig_i_4), C.uintptr_t(_swig_i_5)))
	return swig_r
}

func Event_add(arg1 Struct_SS_event, arg2 Struct_SS_timeval) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_event_add_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Event_remove_timer(arg1 Struct_SS_event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_remove_timer_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_del(arg1 Struct_SS_event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_del_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_del_noblock(arg1 Struct_SS_event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_del_noblock_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_del_block(arg1 Struct_SS_event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_del_block_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_active(arg1 Struct_SS_event, arg2 int, arg3 int16) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_event_active_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.short(_swig_i_2))
}

func Event_pending(arg1 Struct_SS_event, arg2 int16, arg3 Struct_SS_timeval) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (int)(C._wrap_event_pending_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.short(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Event_base_get_running_event(arg1 Struct_SS_event_base) (_swig_ret Struct_SS_event) {
	var swig_r Struct_SS_event
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_event)(SwigcptrStruct_SS_event(C._wrap_event_base_get_running_event_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Event_initialized(arg1 Struct_SS_event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_initialized_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_get_fd(arg1 Struct_SS_event) (_swig_ret Evutil_socket_t) {
	var swig_r Evutil_socket_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Evutil_socket_t)(SwigcptrEvutil_socket_t(C._wrap_event_get_fd_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Event_get_base(arg1 Struct_SS_event) (_swig_ret Struct_SS_event_base) {
	var swig_r Struct_SS_event_base
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Struct_SS_event_base)(SwigcptrStruct_SS_event_base(C._wrap_event_get_base_libevent_f475800292a41471(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Event_get_events(arg1 Struct_SS_event) (_swig_ret int16) {
	var swig_r int16
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int16)(C._wrap_event_get_events_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_get_callback(arg1 Struct_SS_event) (_swig_ret *_swig_fnptr) {
	var swig_r *_swig_fnptr
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (*_swig_fnptr)(C._wrap_event_get_callback_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_get_callback_arg(arg1 Struct_SS_event) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uintptr)(C._wrap_event_get_callback_arg_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_get_priority(arg1 Struct_SS_event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_get_priority_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_get_assignment(arg1 Struct_SS_event, arg2 Struct_SS_event_base, arg3 Evutil_socket_t, arg4 *int16, arg5 *_swig_fnptr, arg6 *uintptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	C._wrap_event_get_assignment_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5))
}

func Event_get_struct_event_size() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_event_get_struct_event_size_libevent_f475800292a41471())
	return swig_r
}

func Event_get_version() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_event_get_version_libevent_f475800292a41471()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Event_get_version_number() (_swig_ret Ev_uint32_t) {
	var swig_r Ev_uint32_t
	swig_r = (Ev_uint32_t)(SwigcptrEv_uint32_t(C._wrap_event_get_version_number_libevent_f475800292a41471()))
	return swig_r
}

const EVENT_MAX_PRIORITIES int = 256
func Event_base_priority_init(arg1 Struct_SS_event_base, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_event_base_priority_init_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Event_base_get_npriorities(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_base_get_npriorities_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Event_priority_set(arg1 Struct_SS_event, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_event_priority_set_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Event_base_init_common_timeout(arg1 Struct_SS_event_base, arg2 Struct_SS_timeval) (_swig_ret Struct_SS_timeval) {
	var swig_r Struct_SS_timeval
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Struct_SS_timeval)(SwigcptrStruct_SS_timeval(C._wrap_event_base_init_common_timeout_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Event_set_mem_functions(arg1 _swig_fnptr, arg2 _swig_fnptr, arg3 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_event_set_mem_functions_libevent_f475800292a41471(C.swig_type_67(_swig_i_0), C.swig_type_68(_swig_i_1), C.swig_type_69(_swig_i_2))
}

func Event_base_dump_events(arg1 Struct_SS_event_base, arg2 FILE) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_event_base_dump_events_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Event_base_active_by_fd(arg1 Struct_SS_event_base, arg2 Evutil_socket_t, arg3 int16) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_event_base_active_by_fd_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.short(_swig_i_2))
}

func Event_base_active_by_signal(arg1 Struct_SS_event_base, arg2 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_event_base_active_by_signal_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Event_base_foreach_event(arg1 Struct_SS_event_base, arg2 *_swig_fnptr, arg3 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_event_base_foreach_event_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Event_base_gettimeofday_cached(arg1 Struct_SS_event_base, arg2 Struct_SS_timeval) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_event_base_gettimeofday_cached_libevent_f475800292a41471(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Event_base_update_cache_time(arg1 Struct_SS_event_base) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_event_base_update_cache_time_libevent_f475800292a41471(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Libevent_global_shutdown() {
	C._wrap_libevent_global_shutdown_libevent_f475800292a41471()
}


type SwigcptrStruct_SS_evhttp_connection uintptr
type Struct_SS_evhttp_connection interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evhttp_connection) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrEv_ssize_t uintptr
type Ev_ssize_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrEv_ssize_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrEv_uint16_t uintptr
type Ev_uint16_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrEv_uint16_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_evhttp_uri uintptr
type Struct_SS_evhttp_uri interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evhttp_uri) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_evhttp_bound_socket uintptr
type Struct_SS_evhttp_bound_socket interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evhttp_bound_socket) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrEv_uint32_t uintptr
type Ev_uint32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrEv_uint32_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_bufferevent uintptr
type Struct_SS_bufferevent interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_bufferevent) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrFILE uintptr
type FILE interface {
	Swigcptr() uintptr;
}
func (p SwigcptrFILE) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrEvutil_socket_t uintptr
type Evutil_socket_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrEvutil_socket_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_evdns_base uintptr
type Struct_SS_evdns_base interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evdns_base) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_evconnlistener uintptr
type Struct_SS_evconnlistener interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evconnlistener) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_timeval uintptr
type Struct_SS_timeval interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_timeval) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_event_base uintptr
type Struct_SS_event_base interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_event_base) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_evhttp uintptr
type Struct_SS_evhttp interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evhttp) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_evhttp_request uintptr
type Struct_SS_evhttp_request interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evhttp_request) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_evkeyvalq uintptr
type Struct_SS_evkeyvalq interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evkeyvalq) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_event_config uintptr
type Struct_SS_event_config interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_event_config) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_sockaddr uintptr
type Struct_SS_sockaddr interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_sockaddr) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_evbuffer uintptr
type Struct_SS_evbuffer interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_evbuffer) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_event uintptr
type Struct_SS_event interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_event) Swigcptr() uintptr {
	return uintptr(p)
}

