/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: libevent.i */

#define SWIGMODULE libevent
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <event2/visibility.h>
#include <event2/http.h>
#include <event2/event.h>

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_libevent_f475800292a41471(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_libevent_f475800292a41471(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


struct evhttp *_wrap_evhttp_new_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct evhttp *result = 0 ;
  struct evhttp *_swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (struct evhttp *)evhttp_new(arg1);
  *(struct evhttp **)&_swig_go_result = (struct evhttp *)result; 
  return _swig_go_result;
}


intgo _wrap_evhttp_bind_socket_libevent_f475800292a41471(struct evhttp *_swig_go_0, _gostring_ _swig_go_1, ev_uint16_t *_swig_go_2) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  char *arg2 = (char *) 0 ;
  ev_uint16_t arg3 ;
  ev_uint16_t *argp3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  argp3 = (ev_uint16_t *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_uint16_t");
  }
  arg3 = (ev_uint16_t)*argp3;
  
  
  result = (int)evhttp_bind_socket(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


struct evhttp_bound_socket *_wrap_evhttp_bind_socket_with_handle_libevent_f475800292a41471(struct evhttp *_swig_go_0, _gostring_ _swig_go_1, ev_uint16_t *_swig_go_2) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  char *arg2 = (char *) 0 ;
  ev_uint16_t arg3 ;
  ev_uint16_t *argp3 ;
  struct evhttp_bound_socket *result = 0 ;
  struct evhttp_bound_socket *_swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  argp3 = (ev_uint16_t *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_uint16_t");
  }
  arg3 = (ev_uint16_t)*argp3;
  
  
  result = (struct evhttp_bound_socket *)evhttp_bind_socket_with_handle(arg1,(char const *)arg2,arg3);
  *(struct evhttp_bound_socket **)&_swig_go_result = (struct evhttp_bound_socket *)result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_accept_socket_libevent_f475800292a41471(struct evhttp *_swig_go_0, evutil_socket_t *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  evutil_socket_t arg2 ;
  evutil_socket_t *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  argp2 = (evutil_socket_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null evutil_socket_t");
  }
  arg2 = (evutil_socket_t)*argp2;
  
  
  result = (int)evhttp_accept_socket(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct evhttp_bound_socket *_wrap_evhttp_accept_socket_with_handle_libevent_f475800292a41471(struct evhttp *_swig_go_0, evutil_socket_t *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  evutil_socket_t arg2 ;
  evutil_socket_t *argp2 ;
  struct evhttp_bound_socket *result = 0 ;
  struct evhttp_bound_socket *_swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  argp2 = (evutil_socket_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null evutil_socket_t");
  }
  arg2 = (evutil_socket_t)*argp2;
  
  
  result = (struct evhttp_bound_socket *)evhttp_accept_socket_with_handle(arg1,arg2);
  *(struct evhttp_bound_socket **)&_swig_go_result = (struct evhttp_bound_socket *)result; 
  return _swig_go_result;
}


struct evhttp_bound_socket *_wrap_evhttp_bind_listener_libevent_f475800292a41471(struct evhttp *_swig_go_0, struct evconnlistener *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  struct evconnlistener *arg2 = (struct evconnlistener *) 0 ;
  struct evhttp_bound_socket *result = 0 ;
  struct evhttp_bound_socket *_swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = *(struct evconnlistener **)&_swig_go_1; 
  
  result = (struct evhttp_bound_socket *)evhttp_bind_listener(arg1,arg2);
  *(struct evhttp_bound_socket **)&_swig_go_result = (struct evhttp_bound_socket *)result; 
  return _swig_go_result;
}


struct evconnlistener *_wrap_evhttp_bound_socket_get_listener_libevent_f475800292a41471(struct evhttp_bound_socket *_swig_go_0) {
  struct evhttp_bound_socket *arg1 = (struct evhttp_bound_socket *) 0 ;
  struct evconnlistener *result = 0 ;
  struct evconnlistener *_swig_go_result;
  
  arg1 = *(struct evhttp_bound_socket **)&_swig_go_0; 
  
  result = (struct evconnlistener *)evhttp_bound_socket_get_listener(arg1);
  *(struct evconnlistener **)&_swig_go_result = (struct evconnlistener *)result; 
  return _swig_go_result;
}


void _wrap_evhttp_foreach_bound_socket_libevent_f475800292a41471(struct evhttp *_swig_go_0, void** _swig_go_1, void *_swig_go_2) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  evhttp_bound_socket_foreach_fn *arg2 = (evhttp_bound_socket_foreach_fn *) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = *(evhttp_bound_socket_foreach_fn **)&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  evhttp_foreach_bound_socket(arg1,arg2,arg3);
  
}


void _wrap_evhttp_del_accept_socket_libevent_f475800292a41471(struct evhttp *_swig_go_0, struct evhttp_bound_socket *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  struct evhttp_bound_socket *arg2 = (struct evhttp_bound_socket *) 0 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = *(struct evhttp_bound_socket **)&_swig_go_1; 
  
  evhttp_del_accept_socket(arg1,arg2);
  
}


evutil_socket_t *_wrap_evhttp_bound_socket_get_fd_libevent_f475800292a41471(struct evhttp_bound_socket *_swig_go_0) {
  struct evhttp_bound_socket *arg1 = (struct evhttp_bound_socket *) 0 ;
  evutil_socket_t result;
  evutil_socket_t *_swig_go_result;
  
  arg1 = *(struct evhttp_bound_socket **)&_swig_go_0; 
  
  result = evhttp_bound_socket_get_fd(arg1);
  {
    evutil_socket_t * resultptr = (evutil_socket_t *)malloc(sizeof(evutil_socket_t));
    memmove(resultptr, &result, sizeof(evutil_socket_t));
    *(evutil_socket_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_evhttp_free_libevent_f475800292a41471(struct evhttp *_swig_go_0) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  evhttp_free(arg1);
  
}


void _wrap_evhttp_set_max_headers_size_libevent_f475800292a41471(struct evhttp *_swig_go_0, ev_ssize_t *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  ev_ssize_t arg2 ;
  ev_ssize_t *argp2 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  argp2 = (ev_ssize_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_ssize_t");
  }
  arg2 = (ev_ssize_t)*argp2;
  
  
  evhttp_set_max_headers_size(arg1,arg2);
  
}


void _wrap_evhttp_set_max_body_size_libevent_f475800292a41471(struct evhttp *_swig_go_0, ev_ssize_t *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  ev_ssize_t arg2 ;
  ev_ssize_t *argp2 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  argp2 = (ev_ssize_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_ssize_t");
  }
  arg2 = (ev_ssize_t)*argp2;
  
  
  evhttp_set_max_body_size(arg1,arg2);
  
}


void _wrap_evhttp_set_default_content_type_libevent_f475800292a41471(struct evhttp *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  evhttp_set_default_content_type(arg1,(char const *)arg2);
  
  free(arg2); 
}


void _wrap_evhttp_set_allowed_methods_libevent_f475800292a41471(struct evhttp *_swig_go_0, ev_uint16_t *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  ev_uint16_t arg2 ;
  ev_uint16_t *argp2 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  argp2 = (ev_uint16_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_uint16_t");
  }
  arg2 = (ev_uint16_t)*argp2;
  
  
  evhttp_set_allowed_methods(arg1,arg2);
  
}


intgo _wrap_evhttp_set_cb_libevent_f475800292a41471(struct evhttp *_swig_go_0, _gostring_ _swig_go_1, void* _swig_go_2, void *_swig_go_3) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  char *arg2 = (char *) 0 ;
  void (*arg3)(struct evhttp_request *,void *) = (void (*)(struct evhttp_request *,void *)) 0 ;
  void *arg4 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(void (**)(struct evhttp_request *,void *))&_swig_go_2; 
  arg4 = *(void **)&_swig_go_3; 
  
  result = (int)evhttp_set_cb(arg1,(char const *)arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_del_cb_libevent_f475800292a41471(struct evhttp *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_del_cb(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_evhttp_set_gencb_libevent_f475800292a41471(struct evhttp *_swig_go_0, void* _swig_go_1, void *_swig_go_2) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  void (*arg2)(struct evhttp_request *,void *) = (void (*)(struct evhttp_request *,void *)) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = *(void (**)(struct evhttp_request *,void *))&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  evhttp_set_gencb(arg1,arg2,arg3);
  
}


void _wrap_evhttp_set_bevcb_libevent_f475800292a41471(struct evhttp *_swig_go_0, void* _swig_go_1, void *_swig_go_2) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  struct bufferevent *(*arg2)(struct event_base *,void *) = (struct bufferevent *(*)(struct event_base *,void *)) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = *(struct bufferevent *(**)(struct event_base *,void *))&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  evhttp_set_bevcb(arg1,arg2,arg3);
  
}


intgo _wrap_evhttp_add_virtual_host_libevent_f475800292a41471(struct evhttp *_swig_go_0, _gostring_ _swig_go_1, struct evhttp *_swig_go_2) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  char *arg2 = (char *) 0 ;
  struct evhttp *arg3 = (struct evhttp *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(struct evhttp **)&_swig_go_2; 
  
  result = (int)evhttp_add_virtual_host(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_remove_virtual_host_libevent_f475800292a41471(struct evhttp *_swig_go_0, struct evhttp *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  struct evhttp *arg2 = (struct evhttp *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = *(struct evhttp **)&_swig_go_1; 
  
  result = (int)evhttp_remove_virtual_host(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_evhttp_add_server_alias_libevent_f475800292a41471(struct evhttp *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_add_server_alias(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_remove_server_alias_libevent_f475800292a41471(struct evhttp *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_remove_server_alias(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_evhttp_set_timeout_libevent_f475800292a41471(struct evhttp *_swig_go_0, intgo _swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  int arg2 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  evhttp_set_timeout(arg1,arg2);
  
}


void _wrap_evhttp_set_timeout_tv_libevent_f475800292a41471(struct evhttp *_swig_go_0, struct timeval *_swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  
  evhttp_set_timeout_tv(arg1,(struct timeval const *)arg2);
  
}


intgo _wrap_evhttp_set_flags_libevent_f475800292a41471(struct evhttp *_swig_go_0, intgo _swig_go_1) {
  struct evhttp *arg1 = (struct evhttp *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)evhttp_set_flags(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_evhttp_send_error_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  evhttp_send_error(arg1,arg2,(char const *)arg3);
  
  free(arg3); 
}


void _wrap_evhttp_send_reply_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2, struct evbuffer *_swig_go_3) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  struct evbuffer *arg4 = (struct evbuffer *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = *(struct evbuffer **)&_swig_go_3; 
  
  evhttp_send_reply(arg1,arg2,(char const *)arg3,arg4);
  
  free(arg3); 
}


void _wrap_evhttp_send_reply_start_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  evhttp_send_reply_start(arg1,arg2,(char const *)arg3);
  
  free(arg3); 
}


void _wrap_evhttp_send_reply_chunk_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, struct evbuffer *_swig_go_1) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  struct evbuffer *arg2 = (struct evbuffer *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = *(struct evbuffer **)&_swig_go_1; 
  
  evhttp_send_reply_chunk(arg1,arg2);
  
}


void _wrap_evhttp_send_reply_chunk_with_cb_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, struct evbuffer *_swig_go_1, void* _swig_go_2, void *_swig_go_3) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  struct evbuffer *arg2 = (struct evbuffer *) 0 ;
  void (*arg3)(struct evhttp_connection *,void *) = (void (*)(struct evhttp_connection *,void *)) 0 ;
  void *arg4 = (void *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = *(struct evbuffer **)&_swig_go_1; 
  arg3 = *(void (**)(struct evhttp_connection *,void *))&_swig_go_2; 
  arg4 = *(void **)&_swig_go_3; 
  
  evhttp_send_reply_chunk_with_cb(arg1,arg2,arg3,arg4);
  
}


void _wrap_evhttp_send_reply_end_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  evhttp_send_reply_end(arg1);
  
}


intgo _wrap_EVHTTP_REQ_GET_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_GET;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQ_POST_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_POST;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQ_HEAD_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_HEAD;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQ_PUT_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_PUT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQ_DELETE_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_DELETE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQ_OPTIONS_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_OPTIONS;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQ_TRACE_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_TRACE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQ_CONNECT_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_CONNECT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQ_PATCH_libevent_f475800292a41471() {
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQ_PATCH;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_REQUEST_libevent_f475800292a41471() {
  enum evhttp_request_kind result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_REQUEST;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVHTTP_RESPONSE_libevent_f475800292a41471() {
  enum evhttp_request_kind result;
  intgo _swig_go_result;
  
  
  result = EVHTTP_RESPONSE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


struct evhttp_connection *_wrap_evhttp_connection_base_bufferevent_new_libevent_f475800292a41471(struct event_base *_swig_go_0, struct evdns_base *_swig_go_1, struct bufferevent *_swig_go_2, _gostring_ _swig_go_3, ev_uint16_t *_swig_go_4) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct evdns_base *arg2 = (struct evdns_base *) 0 ;
  struct bufferevent *arg3 = (struct bufferevent *) 0 ;
  char *arg4 = (char *) 0 ;
  ev_uint16_t arg5 ;
  ev_uint16_t *argp5 ;
  struct evhttp_connection *result = 0 ;
  struct evhttp_connection *_swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(struct evdns_base **)&_swig_go_1; 
  arg3 = *(struct bufferevent **)&_swig_go_2; 
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  argp5 = (ev_uint16_t *)_swig_go_4;
  if (argp5 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_uint16_t");
  }
  arg5 = (ev_uint16_t)*argp5;
  
  
  result = (struct evhttp_connection *)evhttp_connection_base_bufferevent_new(arg1,arg2,arg3,(char const *)arg4,arg5);
  *(struct evhttp_connection **)&_swig_go_result = (struct evhttp_connection *)result; 
  free(arg4); 
  return _swig_go_result;
}


struct bufferevent *_wrap_evhttp_connection_get_bufferevent_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  struct bufferevent *result = 0 ;
  struct bufferevent *_swig_go_result;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  result = (struct bufferevent *)evhttp_connection_get_bufferevent(arg1);
  *(struct bufferevent **)&_swig_go_result = (struct bufferevent *)result; 
  return _swig_go_result;
}


struct evhttp *_wrap_evhttp_connection_get_server_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  struct evhttp *result = 0 ;
  struct evhttp *_swig_go_result;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  result = (struct evhttp *)evhttp_connection_get_server(arg1);
  *(struct evhttp **)&_swig_go_result = (struct evhttp *)result; 
  return _swig_go_result;
}


struct evhttp_request *_wrap_evhttp_request_new_libevent_f475800292a41471(void* _swig_go_0, void *_swig_go_1) {
  void (*arg1)(struct evhttp_request *,void *) = (void (*)(struct evhttp_request *,void *)) 0 ;
  void *arg2 = (void *) 0 ;
  struct evhttp_request *result = 0 ;
  struct evhttp_request *_swig_go_result;
  
  arg1 = *(void (**)(struct evhttp_request *,void *))&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  result = (struct evhttp_request *)evhttp_request_new(arg1,arg2);
  *(struct evhttp_request **)&_swig_go_result = (struct evhttp_request *)result; 
  return _swig_go_result;
}


void _wrap_evhttp_request_set_chunked_cb_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, void* _swig_go_1) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  void (*arg2)(struct evhttp_request *,void *) = (void (*)(struct evhttp_request *,void *)) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = *(void (**)(struct evhttp_request *,void *))&_swig_go_1; 
  
  evhttp_request_set_chunked_cb(arg1,arg2);
  
}


void _wrap_evhttp_request_set_header_cb_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, void* _swig_go_1) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  int (*arg2)(struct evhttp_request *,void *) = (int (*)(struct evhttp_request *,void *)) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = *(int (**)(struct evhttp_request *,void *))&_swig_go_1; 
  
  evhttp_request_set_header_cb(arg1,arg2);
  
}


intgo _wrap_EVREQ_HTTP_TIMEOUT_libevent_f475800292a41471() {
  enum evhttp_request_error result;
  intgo _swig_go_result;
  
  
  result = EVREQ_HTTP_TIMEOUT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVREQ_HTTP_EOF_libevent_f475800292a41471() {
  enum evhttp_request_error result;
  intgo _swig_go_result;
  
  
  result = EVREQ_HTTP_EOF;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVREQ_HTTP_INVALID_HEADER_libevent_f475800292a41471() {
  enum evhttp_request_error result;
  intgo _swig_go_result;
  
  
  result = EVREQ_HTTP_INVALID_HEADER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVREQ_HTTP_BUFFER_ERROR_libevent_f475800292a41471() {
  enum evhttp_request_error result;
  intgo _swig_go_result;
  
  
  result = EVREQ_HTTP_BUFFER_ERROR;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVREQ_HTTP_REQUEST_CANCEL_libevent_f475800292a41471() {
  enum evhttp_request_error result;
  intgo _swig_go_result;
  
  
  result = EVREQ_HTTP_REQUEST_CANCEL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVREQ_HTTP_DATA_TOO_LONG_libevent_f475800292a41471() {
  enum evhttp_request_error result;
  intgo _swig_go_result;
  
  
  result = EVREQ_HTTP_DATA_TOO_LONG;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_evhttp_request_set_error_cb_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, void* _swig_go_1) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  void (*arg2)(enum evhttp_request_error,void *) = (void (*)(enum evhttp_request_error,void *)) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = *(void (**)(enum evhttp_request_error,void *))&_swig_go_1; 
  
  evhttp_request_set_error_cb(arg1,arg2);
  
}


void _wrap_evhttp_request_set_on_complete_cb_libevent_f475800292a41471(struct evhttp_request *_swig_go_0, void* _swig_go_1, void *_swig_go_2) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  void (*arg2)(struct evhttp_request *,void *) = (void (*)(struct evhttp_request *,void *)) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  arg2 = *(void (**)(struct evhttp_request *,void *))&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  evhttp_request_set_on_complete_cb(arg1,arg2,arg3);
  
}


void _wrap_evhttp_request_free_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  evhttp_request_free(arg1);
  
}


struct evhttp_connection *_wrap_evhttp_connection_base_new_libevent_f475800292a41471(struct event_base *_swig_go_0, struct evdns_base *_swig_go_1, _gostring_ _swig_go_2, ev_uint16_t *_swig_go_3) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct evdns_base *arg2 = (struct evdns_base *) 0 ;
  char *arg3 = (char *) 0 ;
  ev_uint16_t arg4 ;
  ev_uint16_t *argp4 ;
  struct evhttp_connection *result = 0 ;
  struct evhttp_connection *_swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(struct evdns_base **)&_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  argp4 = (ev_uint16_t *)_swig_go_3;
  if (argp4 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_uint16_t");
  }
  arg4 = (ev_uint16_t)*argp4;
  
  
  result = (struct evhttp_connection *)evhttp_connection_base_new(arg1,arg2,(char const *)arg3,arg4);
  *(struct evhttp_connection **)&_swig_go_result = (struct evhttp_connection *)result; 
  free(arg3); 
  return _swig_go_result;
}


void _wrap_evhttp_connection_set_family_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, intgo _swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  int arg2 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  evhttp_connection_set_family(arg1,arg2);
  
}


intgo _wrap_evhttp_connection_set_flags_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, intgo _swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)evhttp_connection_set_flags(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_evhttp_request_own_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  evhttp_request_own(arg1);
  
}


intgo _wrap_evhttp_request_is_owned_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (int)evhttp_request_is_owned(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct evhttp_connection *_wrap_evhttp_request_get_connection_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  struct evhttp_connection *result = 0 ;
  struct evhttp_connection *_swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (struct evhttp_connection *)evhttp_request_get_connection(arg1);
  *(struct evhttp_connection **)&_swig_go_result = (struct evhttp_connection *)result; 
  return _swig_go_result;
}


struct event_base *_wrap_evhttp_connection_get_base_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  struct event_base *result = 0 ;
  struct event_base *_swig_go_result;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  result = (struct event_base *)evhttp_connection_get_base(arg1);
  *(struct event_base **)&_swig_go_result = (struct event_base *)result; 
  return _swig_go_result;
}


void _wrap_evhttp_connection_set_max_headers_size_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, ev_ssize_t *_swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  ev_ssize_t arg2 ;
  ev_ssize_t *argp2 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  argp2 = (ev_ssize_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_ssize_t");
  }
  arg2 = (ev_ssize_t)*argp2;
  
  
  evhttp_connection_set_max_headers_size(arg1,arg2);
  
}


void _wrap_evhttp_connection_set_max_body_size_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, ev_ssize_t *_swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  ev_ssize_t arg2 ;
  ev_ssize_t *argp2 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  argp2 = (ev_ssize_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_ssize_t");
  }
  arg2 = (ev_ssize_t)*argp2;
  
  
  evhttp_connection_set_max_body_size(arg1,arg2);
  
}


void _wrap_evhttp_connection_free_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  evhttp_connection_free(arg1);
  
}


void _wrap_evhttp_connection_free_on_completion_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  evhttp_connection_free_on_completion(arg1);
  
}


void _wrap_evhttp_connection_set_local_address_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  evhttp_connection_set_local_address(arg1,(char const *)arg2);
  
  free(arg2); 
}


void _wrap_evhttp_connection_set_local_port_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, ev_uint16_t *_swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  ev_uint16_t arg2 ;
  ev_uint16_t *argp2 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  argp2 = (ev_uint16_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_uint16_t");
  }
  arg2 = (ev_uint16_t)*argp2;
  
  
  evhttp_connection_set_local_port(arg1,arg2);
  
}


void _wrap_evhttp_connection_set_timeout_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, intgo _swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  int arg2 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  evhttp_connection_set_timeout(arg1,arg2);
  
}


void _wrap_evhttp_connection_set_timeout_tv_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, struct timeval *_swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  
  evhttp_connection_set_timeout_tv(arg1,(struct timeval const *)arg2);
  
}


void _wrap_evhttp_connection_set_initial_retry_tv_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, struct timeval *_swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  
  evhttp_connection_set_initial_retry_tv(arg1,(struct timeval const *)arg2);
  
}


void _wrap_evhttp_connection_set_retries_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, intgo _swig_go_1) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  int arg2 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  evhttp_connection_set_retries(arg1,arg2);
  
}


void _wrap_evhttp_connection_set_closecb_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, void* _swig_go_1, void *_swig_go_2) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  void (*arg2)(struct evhttp_connection *,void *) = (void (*)(struct evhttp_connection *,void *)) 0 ;
  void *arg3 = (void *) 0 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = *(void (**)(struct evhttp_connection *,void *))&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  evhttp_connection_set_closecb(arg1,arg2,arg3);
  
}


void _wrap_evhttp_connection_get_peer_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, _gostring_* _swig_go_1, ev_uint16_t *_swig_go_2) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  char **arg2 = (char **) 0 ;
  ev_uint16_t *arg3 = (ev_uint16_t *) 0 ;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = *(char ***)&_swig_go_1; 
  arg3 = *(ev_uint16_t **)&_swig_go_2; 
  
  evhttp_connection_get_peer(arg1,arg2,arg3);
  
}


struct sockaddr *_wrap_evhttp_connection_get_addr_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  struct sockaddr *result = 0 ;
  struct sockaddr *_swig_go_result;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  
  result = (struct sockaddr *)evhttp_connection_get_addr(arg1);
  *(struct sockaddr **)&_swig_go_result = (struct sockaddr *)result; 
  return _swig_go_result;
}


intgo _wrap_evhttp_make_request_libevent_f475800292a41471(struct evhttp_connection *_swig_go_0, struct evhttp_request *_swig_go_1, intgo _swig_go_2, _gostring_ _swig_go_3) {
  struct evhttp_connection *arg1 = (struct evhttp_connection *) 0 ;
  struct evhttp_request *arg2 = (struct evhttp_request *) 0 ;
  enum evhttp_cmd_type arg3 ;
  char *arg4 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_connection **)&_swig_go_0; 
  arg2 = *(struct evhttp_request **)&_swig_go_1; 
  arg3 = (enum evhttp_cmd_type)_swig_go_2; 
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  result = (int)evhttp_make_request(arg1,arg2,arg3,(char const *)arg4);
  _swig_go_result = result; 
  free(arg4); 
  return _swig_go_result;
}


void _wrap_evhttp_cancel_request_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  evhttp_cancel_request(arg1);
  
}


_gostring_ _wrap_evhttp_request_get_uri_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (char *)evhttp_request_get_uri((struct evhttp_request const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


struct evhttp_uri *_wrap_evhttp_request_get_evhttp_uri_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  struct evhttp_uri *result = 0 ;
  struct evhttp_uri *_swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (struct evhttp_uri *)evhttp_request_get_evhttp_uri((struct evhttp_request const *)arg1);
  *(struct evhttp_uri **)&_swig_go_result = (struct evhttp_uri *)result; 
  return _swig_go_result;
}


intgo _wrap_evhttp_request_get_command_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  enum evhttp_cmd_type result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (enum evhttp_cmd_type)evhttp_request_get_command((struct evhttp_request const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_evhttp_request_get_response_code_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (int)evhttp_request_get_response_code((struct evhttp_request const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_request_get_response_code_line_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (char *)evhttp_request_get_response_code_line((struct evhttp_request const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


struct evkeyvalq *_wrap_evhttp_request_get_input_headers_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  struct evkeyvalq *result = 0 ;
  struct evkeyvalq *_swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (struct evkeyvalq *)evhttp_request_get_input_headers(arg1);
  *(struct evkeyvalq **)&_swig_go_result = (struct evkeyvalq *)result; 
  return _swig_go_result;
}


struct evkeyvalq *_wrap_evhttp_request_get_output_headers_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  struct evkeyvalq *result = 0 ;
  struct evkeyvalq *_swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (struct evkeyvalq *)evhttp_request_get_output_headers(arg1);
  *(struct evkeyvalq **)&_swig_go_result = (struct evkeyvalq *)result; 
  return _swig_go_result;
}


struct evbuffer *_wrap_evhttp_request_get_input_buffer_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  struct evbuffer *result = 0 ;
  struct evbuffer *_swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (struct evbuffer *)evhttp_request_get_input_buffer(arg1);
  *(struct evbuffer **)&_swig_go_result = (struct evbuffer *)result; 
  return _swig_go_result;
}


struct evbuffer *_wrap_evhttp_request_get_output_buffer_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  struct evbuffer *result = 0 ;
  struct evbuffer *_swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (struct evbuffer *)evhttp_request_get_output_buffer(arg1);
  *(struct evbuffer **)&_swig_go_result = (struct evbuffer *)result; 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_request_get_host_libevent_f475800292a41471(struct evhttp_request *_swig_go_0) {
  struct evhttp_request *arg1 = (struct evhttp_request *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_request **)&_swig_go_0; 
  
  result = (char *)evhttp_request_get_host(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_find_header_libevent_f475800292a41471(struct evkeyvalq *_swig_go_0, _gostring_ _swig_go_1) {
  struct evkeyvalq *arg1 = (struct evkeyvalq *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evkeyvalq **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (char *)evhttp_find_header((struct evkeyvalq const *)arg1,(char const *)arg2);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_remove_header_libevent_f475800292a41471(struct evkeyvalq *_swig_go_0, _gostring_ _swig_go_1) {
  struct evkeyvalq *arg1 = (struct evkeyvalq *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evkeyvalq **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_remove_header(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_add_header_libevent_f475800292a41471(struct evkeyvalq *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2) {
  struct evkeyvalq *arg1 = (struct evkeyvalq *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evkeyvalq **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (int)evhttp_add_header(arg1,(char const *)arg2,(char const *)arg3);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


void _wrap_evhttp_clear_headers_libevent_f475800292a41471(struct evkeyvalq *_swig_go_0) {
  struct evkeyvalq *arg1 = (struct evkeyvalq *) 0 ;
  
  arg1 = *(struct evkeyvalq **)&_swig_go_0; 
  
  evhttp_clear_headers(arg1);
  
}


_gostring_ _wrap_evhttp_encode_uri_libevent_f475800292a41471(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (char *)evhttp_encode_uri((char const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(arg1); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_uriencode_libevent_f475800292a41471(_gostring_ _swig_go_0, ev_ssize_t *_swig_go_1, intgo _swig_go_2) {
  char *arg1 = (char *) 0 ;
  ev_ssize_t arg2 ;
  int arg3 ;
  ev_ssize_t *argp2 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  argp2 = (ev_ssize_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_ssize_t");
  }
  arg2 = (ev_ssize_t)*argp2;
  
  arg3 = (int)_swig_go_2; 
  
  result = (char *)evhttp_uriencode((char const *)arg1,arg2,arg3);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(arg1); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_decode_uri_libevent_f475800292a41471(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (char *)evhttp_decode_uri((char const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(arg1); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_uridecode_libevent_f475800292a41471(_gostring_ _swig_go_0, intgo _swig_go_1, long long *_swig_go_2) {
  char *arg1 = (char *) 0 ;
  int arg2 ;
  size_t *arg3 = (size_t *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = (int)_swig_go_1; 
  arg3 = *(size_t **)&_swig_go_2; 
  
  result = (char *)evhttp_uridecode((char const *)arg1,arg2,arg3);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_evhttp_parse_query_libevent_f475800292a41471(_gostring_ _swig_go_0, struct evkeyvalq *_swig_go_1) {
  char *arg1 = (char *) 0 ;
  struct evkeyvalq *arg2 = (struct evkeyvalq *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(struct evkeyvalq **)&_swig_go_1; 
  
  result = (int)evhttp_parse_query((char const *)arg1,arg2);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_evhttp_parse_query_str_libevent_f475800292a41471(_gostring_ _swig_go_0, struct evkeyvalq *_swig_go_1) {
  char *arg1 = (char *) 0 ;
  struct evkeyvalq *arg2 = (struct evkeyvalq *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(struct evkeyvalq **)&_swig_go_1; 
  
  result = (int)evhttp_parse_query_str((char const *)arg1,arg2);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_htmlescape_libevent_f475800292a41471(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (char *)evhttp_htmlescape((char const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(arg1); 
  return _swig_go_result;
}


struct evhttp_uri *_wrap_evhttp_uri_new_libevent_f475800292a41471() {
  struct evhttp_uri *result = 0 ;
  struct evhttp_uri *_swig_go_result;
  
  
  result = (struct evhttp_uri *)evhttp_uri_new();
  *(struct evhttp_uri **)&_swig_go_result = (struct evhttp_uri *)result; 
  return _swig_go_result;
}


void _wrap_evhttp_uri_set_flags_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, intgo _swig_go_1) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  unsigned int arg2 ;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  evhttp_uri_set_flags(arg1,arg2);
  
}


_gostring_ _wrap_evhttp_uri_get_scheme_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  result = (char *)evhttp_uri_get_scheme((struct evhttp_uri const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_uri_get_userinfo_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  result = (char *)evhttp_uri_get_userinfo((struct evhttp_uri const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_uri_get_host_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  result = (char *)evhttp_uri_get_host((struct evhttp_uri const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_evhttp_uri_get_port_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  result = (int)evhttp_uri_get_port((struct evhttp_uri const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_uri_get_path_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  result = (char *)evhttp_uri_get_path((struct evhttp_uri const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_uri_get_query_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  result = (char *)evhttp_uri_get_query((struct evhttp_uri const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_evhttp_uri_get_fragment_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  result = (char *)evhttp_uri_get_fragment((struct evhttp_uri const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_evhttp_uri_set_scheme_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_uri_set_scheme(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_uri_set_userinfo_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_uri_set_userinfo(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_uri_set_host_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_uri_set_host(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_uri_set_port_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, intgo _swig_go_1) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)evhttp_uri_set_port(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_evhttp_uri_set_path_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_uri_set_path(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_uri_set_query_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_uri_set_query(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_evhttp_uri_set_fragment_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, _gostring_ _swig_go_1) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)evhttp_uri_set_fragment(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


struct evhttp_uri *_wrap_evhttp_uri_parse_with_flags_libevent_f475800292a41471(_gostring_ _swig_go_0, intgo _swig_go_1) {
  char *arg1 = (char *) 0 ;
  unsigned int arg2 ;
  struct evhttp_uri *result = 0 ;
  struct evhttp_uri *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = (unsigned int)_swig_go_1; 
  
  result = (struct evhttp_uri *)evhttp_uri_parse_with_flags((char const *)arg1,arg2);
  *(struct evhttp_uri **)&_swig_go_result = (struct evhttp_uri *)result; 
  free(arg1); 
  return _swig_go_result;
}


struct evhttp_uri *_wrap_evhttp_uri_parse_libevent_f475800292a41471(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  struct evhttp_uri *result = 0 ;
  struct evhttp_uri *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (struct evhttp_uri *)evhttp_uri_parse((char const *)arg1);
  *(struct evhttp_uri **)&_swig_go_result = (struct evhttp_uri *)result; 
  free(arg1); 
  return _swig_go_result;
}


void _wrap_evhttp_uri_free_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  evhttp_uri_free(arg1);
  
}


_gostring_ _wrap_evhttp_uri_join_libevent_f475800292a41471(struct evhttp_uri *_swig_go_0, _gostring_ _swig_go_1, long long _swig_go_2) {
  struct evhttp_uri *arg1 = (struct evhttp_uri *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct evhttp_uri **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (size_t)_swig_go_2; 
  
  result = (char *)evhttp_uri_join(arg1,arg2,arg3);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_event_enable_debug_mode_libevent_f475800292a41471() {
  event_enable_debug_mode();
  
}


void _wrap_event_debug_unassign_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  event_debug_unassign(arg1);
  
}


struct event_base *_wrap_event_base_new_libevent_f475800292a41471() {
  struct event_base *result = 0 ;
  struct event_base *_swig_go_result;
  
  
  result = (struct event_base *)event_base_new();
  *(struct event_base **)&_swig_go_result = (struct event_base *)result; 
  return _swig_go_result;
}


intgo _wrap_event_reinit_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_reinit(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_dispatch_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_base_dispatch(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_event_base_get_method_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (char *)event_base_get_method((struct event_base const *)arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_* _wrap_event_get_supported_methods_libevent_f475800292a41471() {
  char **result = 0 ;
  _gostring_* _swig_go_result;
  
  
  result = (char **)event_get_supported_methods();
  *(char ***)&_swig_go_result = (char **)result; 
  return _swig_go_result;
}


intgo _wrap_event_gettime_monotonic_libevent_f475800292a41471(struct event_base *_swig_go_0, struct timeval *_swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  
  result = (int)event_gettime_monotonic(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_get_num_events_libevent_f475800292a41471(struct event_base *_swig_go_0, intgo _swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  unsigned int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  result = (int)event_base_get_num_events(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_get_max_events_libevent_f475800292a41471(struct event_base *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  unsigned int arg2 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)event_base_get_max_events(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct event_config *_wrap_event_config_new_libevent_f475800292a41471() {
  struct event_config *result = 0 ;
  struct event_config *_swig_go_result;
  
  
  result = (struct event_config *)event_config_new();
  *(struct event_config **)&_swig_go_result = (struct event_config *)result; 
  return _swig_go_result;
}


void _wrap_event_config_free_libevent_f475800292a41471(struct event_config *_swig_go_0) {
  struct event_config *arg1 = (struct event_config *) 0 ;
  
  arg1 = *(struct event_config **)&_swig_go_0; 
  
  event_config_free(arg1);
  
}


intgo _wrap_event_config_avoid_method_libevent_f475800292a41471(struct event_config *_swig_go_0, _gostring_ _swig_go_1) {
  struct event_config *arg1 = (struct event_config *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_config **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)event_config_avoid_method(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_EV_FEATURE_ET_libevent_f475800292a41471() {
  enum event_method_feature result;
  intgo _swig_go_result;
  
  
  result = EV_FEATURE_ET;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EV_FEATURE_O1_libevent_f475800292a41471() {
  enum event_method_feature result;
  intgo _swig_go_result;
  
  
  result = EV_FEATURE_O1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EV_FEATURE_FDS_libevent_f475800292a41471() {
  enum event_method_feature result;
  intgo _swig_go_result;
  
  
  result = EV_FEATURE_FDS;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EV_FEATURE_EARLY_CLOSE_libevent_f475800292a41471() {
  enum event_method_feature result;
  intgo _swig_go_result;
  
  
  result = EV_FEATURE_EARLY_CLOSE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVENT_BASE_FLAG_NOLOCK_libevent_f475800292a41471() {
  enum event_base_config_flag result;
  intgo _swig_go_result;
  
  
  result = EVENT_BASE_FLAG_NOLOCK;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVENT_BASE_FLAG_IGNORE_ENV_libevent_f475800292a41471() {
  enum event_base_config_flag result;
  intgo _swig_go_result;
  
  
  result = EVENT_BASE_FLAG_IGNORE_ENV;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVENT_BASE_FLAG_STARTUP_IOCP_libevent_f475800292a41471() {
  enum event_base_config_flag result;
  intgo _swig_go_result;
  
  
  result = EVENT_BASE_FLAG_STARTUP_IOCP;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVENT_BASE_FLAG_NO_CACHE_TIME_libevent_f475800292a41471() {
  enum event_base_config_flag result;
  intgo _swig_go_result;
  
  
  result = EVENT_BASE_FLAG_NO_CACHE_TIME;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVENT_BASE_FLAG_EPOLL_USE_CHANGELIST_libevent_f475800292a41471() {
  enum event_base_config_flag result;
  intgo _swig_go_result;
  
  
  result = EVENT_BASE_FLAG_EPOLL_USE_CHANGELIST;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EVENT_BASE_FLAG_PRECISE_TIMER_libevent_f475800292a41471() {
  enum event_base_config_flag result;
  intgo _swig_go_result;
  
  
  result = EVENT_BASE_FLAG_PRECISE_TIMER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_event_base_get_features_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_base_get_features((struct event_base const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_config_require_features_libevent_f475800292a41471(struct event_config *_swig_go_0, intgo _swig_go_1) {
  struct event_config *arg1 = (struct event_config *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_config **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)event_config_require_features(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_config_set_flag_libevent_f475800292a41471(struct event_config *_swig_go_0, intgo _swig_go_1) {
  struct event_config *arg1 = (struct event_config *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_config **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)event_config_set_flag(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_config_set_num_cpus_hint_libevent_f475800292a41471(struct event_config *_swig_go_0, intgo _swig_go_1) {
  struct event_config *arg1 = (struct event_config *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_config **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)event_config_set_num_cpus_hint(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_config_set_max_dispatch_interval_libevent_f475800292a41471(struct event_config *_swig_go_0, struct timeval *_swig_go_1, intgo _swig_go_2, intgo _swig_go_3) {
  struct event_config *arg1 = (struct event_config *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  int arg3 ;
  int arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_config **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  
  result = (int)event_config_set_max_dispatch_interval(arg1,(struct timeval const *)arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct event_base *_wrap_event_base_new_with_config_libevent_f475800292a41471(struct event_config *_swig_go_0) {
  struct event_config *arg1 = (struct event_config *) 0 ;
  struct event_base *result = 0 ;
  struct event_base *_swig_go_result;
  
  arg1 = *(struct event_config **)&_swig_go_0; 
  
  result = (struct event_base *)event_base_new_with_config((struct event_config const *)arg1);
  *(struct event_base **)&_swig_go_result = (struct event_base *)result; 
  return _swig_go_result;
}


void _wrap_event_base_free_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  event_base_free(arg1);
  
}


void _wrap_event_base_free_nofinalize_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  event_base_free_nofinalize(arg1);
  
}


void _wrap_event_set_log_callback_libevent_f475800292a41471(void** _swig_go_0) {
  event_log_cb arg1 = (event_log_cb) 0 ;
  
  arg1 = *(event_log_cb *)&_swig_go_0; 
  
  event_set_log_callback(arg1);
  
}


void _wrap_event_set_fatal_callback_libevent_f475800292a41471(void** _swig_go_0) {
  event_fatal_cb arg1 = (event_fatal_cb) 0 ;
  
  arg1 = *(event_fatal_cb *)&_swig_go_0; 
  
  event_set_fatal_callback(arg1);
  
}


void _wrap_event_enable_debug_logging_libevent_f475800292a41471(ev_uint32_t *_swig_go_0) {
  ev_uint32_t arg1 ;
  ev_uint32_t *argp1 ;
  
  
  argp1 = (ev_uint32_t *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null ev_uint32_t");
  }
  arg1 = (ev_uint32_t)*argp1;
  
  
  event_enable_debug_logging(arg1);
  
}


intgo _wrap_event_base_set_libevent_f475800292a41471(struct event_base *_swig_go_0, struct event *_swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct event *arg2 = (struct event *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(struct event **)&_swig_go_1; 
  
  result = (int)event_base_set(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_loop_libevent_f475800292a41471(struct event_base *_swig_go_0, intgo _swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)event_base_loop(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_loopexit_libevent_f475800292a41471(struct event_base *_swig_go_0, struct timeval *_swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  
  result = (int)event_base_loopexit(arg1,(struct timeval const *)arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_loopbreak_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_base_loopbreak(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_loopcontinue_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_base_loopcontinue(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_got_exit_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_base_got_exit(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_got_break_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_base_got_break(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void *_wrap_event_self_cbarg_libevent_f475800292a41471() {
  void *result = 0 ;
  void *_swig_go_result;
  
  
  result = (void *)event_self_cbarg();
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


struct event *_wrap_event_new_libevent_f475800292a41471(struct event_base *_swig_go_0, evutil_socket_t *_swig_go_1, short _swig_go_2, void** _swig_go_3, void *_swig_go_4) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  evutil_socket_t arg2 ;
  short arg3 ;
  event_callback_fn arg4 = (event_callback_fn) 0 ;
  void *arg5 = (void *) 0 ;
  evutil_socket_t *argp2 ;
  struct event *result = 0 ;
  struct event *_swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  argp2 = (evutil_socket_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null evutil_socket_t");
  }
  arg2 = (evutil_socket_t)*argp2;
  
  arg3 = (short)_swig_go_2; 
  arg4 = *(event_callback_fn *)&_swig_go_3; 
  arg5 = *(void **)&_swig_go_4; 
  
  result = (struct event *)event_new(arg1,arg2,arg3,arg4,arg5);
  *(struct event **)&_swig_go_result = (struct event *)result; 
  return _swig_go_result;
}


intgo _wrap_event_assign_libevent_f475800292a41471(struct event *_swig_go_0, struct event_base *_swig_go_1, evutil_socket_t *_swig_go_2, short _swig_go_3, void** _swig_go_4, void *_swig_go_5) {
  struct event *arg1 = (struct event *) 0 ;
  struct event_base *arg2 = (struct event_base *) 0 ;
  evutil_socket_t arg3 ;
  short arg4 ;
  event_callback_fn arg5 = (event_callback_fn) 0 ;
  void *arg6 = (void *) 0 ;
  evutil_socket_t *argp3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  arg2 = *(struct event_base **)&_swig_go_1; 
  
  argp3 = (evutil_socket_t *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null evutil_socket_t");
  }
  arg3 = (evutil_socket_t)*argp3;
  
  arg4 = (short)_swig_go_3; 
  arg5 = *(event_callback_fn *)&_swig_go_4; 
  arg6 = *(void **)&_swig_go_5; 
  
  result = (int)event_assign(arg1,arg2,arg3,arg4,arg5,arg6);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_event_free_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  event_free(arg1);
  
}


intgo _wrap_event_finalize_libevent_f475800292a41471(intgo _swig_go_0, struct event *_swig_go_1, void** _swig_go_2) {
  unsigned int arg1 ;
  struct event *arg2 = (struct event *) 0 ;
  event_finalize_callback_fn arg3 = (event_finalize_callback_fn) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  arg2 = *(struct event **)&_swig_go_1; 
  arg3 = *(event_finalize_callback_fn *)&_swig_go_2; 
  
  result = (int)event_finalize(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_free_finalize_libevent_f475800292a41471(intgo _swig_go_0, struct event *_swig_go_1, void** _swig_go_2) {
  unsigned int arg1 ;
  struct event *arg2 = (struct event *) 0 ;
  event_finalize_callback_fn arg3 = (event_finalize_callback_fn) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  arg2 = *(struct event **)&_swig_go_1; 
  arg3 = *(event_finalize_callback_fn *)&_swig_go_2; 
  
  result = (int)event_free_finalize(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_once_libevent_f475800292a41471(struct event_base *_swig_go_0, evutil_socket_t *_swig_go_1, short _swig_go_2, void** _swig_go_3, void *_swig_go_4, struct timeval *_swig_go_5) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  evutil_socket_t arg2 ;
  short arg3 ;
  event_callback_fn arg4 = (event_callback_fn) 0 ;
  void *arg5 = (void *) 0 ;
  struct timeval *arg6 = (struct timeval *) 0 ;
  evutil_socket_t *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  argp2 = (evutil_socket_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null evutil_socket_t");
  }
  arg2 = (evutil_socket_t)*argp2;
  
  arg3 = (short)_swig_go_2; 
  arg4 = *(event_callback_fn *)&_swig_go_3; 
  arg5 = *(void **)&_swig_go_4; 
  arg6 = *(struct timeval **)&_swig_go_5; 
  
  result = (int)event_base_once(arg1,arg2,arg3,arg4,arg5,(struct timeval const *)arg6);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_add_libevent_f475800292a41471(struct event *_swig_go_0, struct timeval *_swig_go_1) {
  struct event *arg1 = (struct event *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  
  result = (int)event_add(arg1,(struct timeval const *)arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_remove_timer_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (int)event_remove_timer(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_del_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (int)event_del(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_del_noblock_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (int)event_del_noblock(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_del_block_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (int)event_del_block(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_event_active_libevent_f475800292a41471(struct event *_swig_go_0, intgo _swig_go_1, short _swig_go_2) {
  struct event *arg1 = (struct event *) 0 ;
  int arg2 ;
  short arg3 ;
  
  arg1 = *(struct event **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (short)_swig_go_2; 
  
  event_active(arg1,arg2,arg3);
  
}


intgo _wrap_event_pending_libevent_f475800292a41471(struct event *_swig_go_0, short _swig_go_1, struct timeval *_swig_go_2) {
  struct event *arg1 = (struct event *) 0 ;
  short arg2 ;
  struct timeval *arg3 = (struct timeval *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  arg2 = (short)_swig_go_1; 
  arg3 = *(struct timeval **)&_swig_go_2; 
  
  result = (int)event_pending((struct event const *)arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct event *_wrap_event_base_get_running_event_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct event *result = 0 ;
  struct event *_swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (struct event *)event_base_get_running_event(arg1);
  *(struct event **)&_swig_go_result = (struct event *)result; 
  return _swig_go_result;
}


intgo _wrap_event_initialized_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (int)event_initialized((struct event const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


evutil_socket_t *_wrap_event_get_fd_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  evutil_socket_t result;
  evutil_socket_t *_swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = event_get_fd((struct event const *)arg1);
  {
    evutil_socket_t * resultptr = (evutil_socket_t *)malloc(sizeof(evutil_socket_t));
    memmove(resultptr, &result, sizeof(evutil_socket_t));
    *(evutil_socket_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct event_base *_wrap_event_get_base_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  struct event_base *result = 0 ;
  struct event_base *_swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (struct event_base *)event_get_base((struct event const *)arg1);
  *(struct event_base **)&_swig_go_result = (struct event_base *)result; 
  return _swig_go_result;
}


short _wrap_event_get_events_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  short result;
  short _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (short)event_get_events((struct event const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void** _wrap_event_get_callback_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  event_callback_fn result;
  void** _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (event_callback_fn)event_get_callback((struct event const *)arg1);
  *(event_callback_fn *)&_swig_go_result = (event_callback_fn)result; 
  return _swig_go_result;
}


void *_wrap_event_get_callback_arg_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (void *)event_get_callback_arg((struct event const *)arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_event_get_priority_libevent_f475800292a41471(struct event *_swig_go_0) {
  struct event *arg1 = (struct event *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  
  result = (int)event_get_priority((struct event const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_event_get_assignment_libevent_f475800292a41471(struct event *_swig_go_0, struct event_base **_swig_go_1, evutil_socket_t *_swig_go_2, short *_swig_go_3, void** _swig_go_4, void **_swig_go_5) {
  struct event *arg1 = (struct event *) 0 ;
  struct event_base **arg2 = (struct event_base **) 0 ;
  evutil_socket_t *arg3 = (evutil_socket_t *) 0 ;
  short *arg4 = (short *) 0 ;
  event_callback_fn *arg5 = (event_callback_fn *) 0 ;
  void **arg6 = (void **) 0 ;
  
  arg1 = *(struct event **)&_swig_go_0; 
  arg2 = *(struct event_base ***)&_swig_go_1; 
  arg3 = *(evutil_socket_t **)&_swig_go_2; 
  arg4 = *(short **)&_swig_go_3; 
  arg5 = *(event_callback_fn **)&_swig_go_4; 
  arg6 = *(void ***)&_swig_go_5; 
  
  event_get_assignment((struct event const *)arg1,arg2,arg3,arg4,arg5,arg6);
  
}


long long _wrap_event_get_struct_event_size_libevent_f475800292a41471() {
  size_t result;
  long long _swig_go_result;
  
  
  result = event_get_struct_event_size();
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_event_get_version_libevent_f475800292a41471() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)event_get_version();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


ev_uint32_t *_wrap_event_get_version_number_libevent_f475800292a41471() {
  ev_uint32_t result;
  ev_uint32_t *_swig_go_result;
  
  
  result = event_get_version_number();
  {
    ev_uint32_t * resultptr = (ev_uint32_t *)malloc(sizeof(ev_uint32_t));
    memmove(resultptr, &result, sizeof(ev_uint32_t));
    *(ev_uint32_t **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


intgo _wrap_event_base_priority_init_libevent_f475800292a41471(struct event_base *_swig_go_0, intgo _swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)event_base_priority_init(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_get_npriorities_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_base_get_npriorities(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_priority_set_libevent_f475800292a41471(struct event *_swig_go_0, intgo _swig_go_1) {
  struct event *arg1 = (struct event *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)event_priority_set(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct timeval *_wrap_event_base_init_common_timeout_libevent_f475800292a41471(struct event_base *_swig_go_0, struct timeval *_swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  struct timeval *result = 0 ;
  struct timeval *_swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  
  result = (struct timeval *)event_base_init_common_timeout(arg1,(struct timeval const *)arg2);
  *(struct timeval **)&_swig_go_result = (struct timeval *)result; 
  return _swig_go_result;
}


void _wrap_event_set_mem_functions_libevent_f475800292a41471(void* _swig_go_0, void* _swig_go_1, void* _swig_go_2) {
  void *(*arg1)(size_t) = (void *(*)(size_t)) 0 ;
  void *(*arg2)(void *,size_t) = (void *(*)(void *,size_t)) 0 ;
  void (*arg3)(void *) = (void (*)(void *)) 0 ;
  
  arg1 = *(void *(**)(size_t))&_swig_go_0; 
  arg2 = *(void *(**)(void *,size_t))&_swig_go_1; 
  arg3 = *(void (**)(void *))&_swig_go_2; 
  
  event_set_mem_functions(arg1,arg2,arg3);
  
}


void _wrap_event_base_dump_events_libevent_f475800292a41471(struct event_base *_swig_go_0, FILE *_swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  FILE *arg2 = (FILE *) 0 ;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(FILE **)&_swig_go_1; 
  
  event_base_dump_events(arg1,arg2);
  
}


void _wrap_event_base_active_by_fd_libevent_f475800292a41471(struct event_base *_swig_go_0, evutil_socket_t *_swig_go_1, short _swig_go_2) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  evutil_socket_t arg2 ;
  short arg3 ;
  evutil_socket_t *argp2 ;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  argp2 = (evutil_socket_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null evutil_socket_t");
  }
  arg2 = (evutil_socket_t)*argp2;
  
  arg3 = (short)_swig_go_2; 
  
  event_base_active_by_fd(arg1,arg2,arg3);
  
}


void _wrap_event_base_active_by_signal_libevent_f475800292a41471(struct event_base *_swig_go_0, intgo _swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int arg2 ;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  event_base_active_by_signal(arg1,arg2);
  
}


intgo _wrap_event_base_foreach_event_libevent_f475800292a41471(struct event_base *_swig_go_0, void** _swig_go_1, void *_swig_go_2) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  event_base_foreach_event_cb arg2 = (event_base_foreach_event_cb) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(event_base_foreach_event_cb *)&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)event_base_foreach_event(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_gettimeofday_cached_libevent_f475800292a41471(struct event_base *_swig_go_0, struct timeval *_swig_go_1) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  struct timeval *arg2 = (struct timeval *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  arg2 = *(struct timeval **)&_swig_go_1; 
  
  result = (int)event_base_gettimeofday_cached(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_event_base_update_cache_time_libevent_f475800292a41471(struct event_base *_swig_go_0) {
  struct event_base *arg1 = (struct event_base *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct event_base **)&_swig_go_0; 
  
  result = (int)event_base_update_cache_time(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_libevent_global_shutdown_libevent_f475800292a41471() {
  libevent_global_shutdown();
  
}


#ifdef __cplusplus
}
#endif

