load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_example",
    srcs = glob(["*.go"]),
    cgo = True,
    importpath = "go_example",
    visibility = ["//visibility:public"],
)
